<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.common.v1.DistinguishedName</code>
 */
class DistinguishedName extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string organization = 1;</code>
     */
    protected $organization = '';
    /**
     * Generated from protobuf field <code>string common_name = 2;</code>
     */
    protected $common_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $organization
     *     @type string $common_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string organization = 1;</code>
     * @return string
     */
    public function getOrganization()
    {
        return $this->organization;
    }

    /**
     * Generated from protobuf field <code>string organization = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrganization($var)
    {
        GPBUtil::checkString($var, True);
        $this->organization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string common_name = 2;</code>
     * @return string
     */
    public function getCommonName()
    {
        return $this->common_name;
    }

    /**
     * Generated from protobuf field <code>string common_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCommonName($var)
    {
        GPBUtil::checkString($var, True);
        $this->common_name = $var;

        return $this;
    }

}

