<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use UnexpectedValueException;

/**
 * Only a subset of the secure hash standard algorithms are supported.
 * See <https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf> for more
 * details.
 * UNSPECIFIED SHOULD not be used, primary reason for inclusion is to force
 * any proto JSON serialization to emit the used hash algorithm, as default
 * option is to *omit* the default value of an enum (which is the first
 * value, represented by '0'.
 *
 * Protobuf type <code>dev.sigstore.common.v1.HashAlgorithm</code>
 */
class HashAlgorithm
{
    /**
     * Generated from protobuf enum <code>HASH_ALGORITHM_UNSPECIFIED = 0;</code>
     */
    const HASH_ALGORITHM_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>SHA2_256 = 1;</code>
     */
    const SHA2_256 = 1;
    /**
     * Generated from protobuf enum <code>SHA2_384 = 2;</code>
     */
    const SHA2_384 = 2;
    /**
     * Generated from protobuf enum <code>SHA2_512 = 3;</code>
     */
    const SHA2_512 = 3;
    /**
     * Generated from protobuf enum <code>SHA3_256 = 4;</code>
     */
    const SHA3_256 = 4;
    /**
     * Generated from protobuf enum <code>SHA3_384 = 5;</code>
     */
    const SHA3_384 = 5;

    private static $valueToName = [
        self::HASH_ALGORITHM_UNSPECIFIED => 'HASH_ALGORITHM_UNSPECIFIED',
        self::SHA2_256 => 'SHA2_256',
        self::SHA2_384 => 'SHA2_384',
        self::SHA2_512 => 'SHA2_512',
        self::SHA3_256 => 'SHA3_256',
        self::SHA3_384 => 'SHA3_384',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

