<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * HashOutput captures a digest of a 'message' (generic octet sequence)
 * and the corresponding hash algorithm used.
 *
 * Generated from protobuf message <code>dev.sigstore.common.v1.HashOutput</code>
 */
class HashOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashAlgorithm algorithm = 1;</code>
     */
    protected $algorithm = 0;
    /**
     * This is the raw octets of the message digest as computed by
     * the hash algorithm.
     *
     * Generated from protobuf field <code>bytes digest = 2;</code>
     */
    protected $digest = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $algorithm
     *     @type string $digest
     *           This is the raw octets of the message digest as computed by
     *           the hash algorithm.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashAlgorithm algorithm = 1;</code>
     * @return int
     */
    public function getAlgorithm()
    {
        return $this->algorithm;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashAlgorithm algorithm = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAlgorithm($var)
    {
        GPBUtil::checkEnum($var, \Dev\Sigstore\Common\V1\HashAlgorithm::class);
        $this->algorithm = $var;

        return $this;
    }

    /**
     * This is the raw octets of the message digest as computed by
     * the hash algorithm.
     *
     * Generated from protobuf field <code>bytes digest = 2;</code>
     * @return string
     */
    public function getDigest()
    {
        return $this->digest;
    }

    /**
     * This is the raw octets of the message digest as computed by
     * the hash algorithm.
     *
     * Generated from protobuf field <code>bytes digest = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDigest($var)
    {
        GPBUtil::checkString($var, False);
        $this->digest = $var;

        return $this;
    }

}

