<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LogId captures the identity of a transparency log.
 *
 * Generated from protobuf message <code>dev.sigstore.common.v1.LogId</code>
 */
class LogId extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identity of the log, represented by its public key.
     *
     * Generated from protobuf field <code>bytes key_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $key_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_id
     *           The unique identity of the log, represented by its public key.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identity of the log, represented by its public key.
     *
     * Generated from protobuf field <code>bytes key_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * The unique identity of the log, represented by its public key.
     *
     * Generated from protobuf field <code>bytes key_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyId($var)
    {
        GPBUtil::checkString($var, False);
        $this->key_id = $var;

        return $this;
    }

}

