<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MessageSignature stores the computed signature over a message.
 *
 * Generated from protobuf message <code>dev.sigstore.common.v1.MessageSignature</code>
 */
class MessageSignature extends \Google\Protobuf\Internal\Message
{
    /**
     * Message digest can be used to identify the artifact.
     * Clients MUST NOT attempt to use this digest to verify the associated
     * signature; it is intended solely for identification.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashOutput message_digest = 1;</code>
     */
    protected $message_digest = null;
    /**
     * The raw bytes as returned from the signature algorithm.
     * The signature algorithm (and so the format of the signature bytes)
     * are determined by the contents of the 'verification_material',
     * either a key-pair or a certificate. If using a certificate, the
     * certificate contains the required information on the signature
     * algorithm.
     * When using a key pair, the algorithm MUST be part of the public
     * key, which MUST be communicated out-of-band.
     *
     * Generated from protobuf field <code>bytes signature = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Dev\Sigstore\Common\V1\HashOutput $message_digest
     *           Message digest can be used to identify the artifact.
     *           Clients MUST NOT attempt to use this digest to verify the associated
     *           signature; it is intended solely for identification.
     *     @type string $signature
     *           The raw bytes as returned from the signature algorithm.
     *           The signature algorithm (and so the format of the signature bytes)
     *           are determined by the contents of the 'verification_material',
     *           either a key-pair or a certificate. If using a certificate, the
     *           certificate contains the required information on the signature
     *           algorithm.
     *           When using a key pair, the algorithm MUST be part of the public
     *           key, which MUST be communicated out-of-band.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Message digest can be used to identify the artifact.
     * Clients MUST NOT attempt to use this digest to verify the associated
     * signature; it is intended solely for identification.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashOutput message_digest = 1;</code>
     * @return \Dev\Sigstore\Common\V1\HashOutput|null
     */
    public function getMessageDigest()
    {
        return $this->message_digest;
    }

    public function hasMessageDigest()
    {
        return isset($this->message_digest);
    }

    public function clearMessageDigest()
    {
        unset($this->message_digest);
    }

    /**
     * Message digest can be used to identify the artifact.
     * Clients MUST NOT attempt to use this digest to verify the associated
     * signature; it is intended solely for identification.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashOutput message_digest = 1;</code>
     * @param \Dev\Sigstore\Common\V1\HashOutput $var
     * @return $this
     */
    public function setMessageDigest($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\HashOutput::class);
        $this->message_digest = $var;

        return $this;
    }

    /**
     * The raw bytes as returned from the signature algorithm.
     * The signature algorithm (and so the format of the signature bytes)
     * are determined by the contents of the 'verification_material',
     * either a key-pair or a certificate. If using a certificate, the
     * certificate contains the required information on the signature
     * algorithm.
     * When using a key pair, the algorithm MUST be part of the public
     * key, which MUST be communicated out-of-band.
     *
     * Generated from protobuf field <code>bytes signature = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * The raw bytes as returned from the signature algorithm.
     * The signature algorithm (and so the format of the signature bytes)
     * are determined by the contents of the 'verification_material',
     * either a key-pair or a certificate. If using a certificate, the
     * certificate contains the required information on the signature
     * algorithm.
     * When using a key pair, the algorithm MUST be part of the public
     * key, which MUST be communicated out-of-band.
     *
     * Generated from protobuf field <code>bytes signature = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

}

