<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An OID and the corresponding (byte) value.
 *
 * Generated from protobuf message <code>dev.sigstore.common.v1.ObjectIdentifierValuePair</code>
 */
class ObjectIdentifierValuePair extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.ObjectIdentifier oid = 1;</code>
     */
    protected $oid = null;
    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Dev\Sigstore\Common\V1\ObjectIdentifier $oid
     *     @type string $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.ObjectIdentifier oid = 1;</code>
     * @return \Dev\Sigstore\Common\V1\ObjectIdentifier|null
     */
    public function getOid()
    {
        return $this->oid;
    }

    public function hasOid()
    {
        return isset($this->oid);
    }

    public function clearOid()
    {
        unset($this->oid);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.ObjectIdentifier oid = 1;</code>
     * @param \Dev\Sigstore\Common\V1\ObjectIdentifier $var
     * @return $this
     */
    public function setOid($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\ObjectIdentifier::class);
        $this->oid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

}

