<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An ASN.1 OBJECT IDENTIFIER
 *
 * Generated from protobuf message <code>dev.sigstore.common.v1.ObjectIdentifier</code>
 */
class ObjectIdentifier extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private $id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>repeated int32 id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->id = $arr;

        return $this;
    }

}

