<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.common.v1.PublicKey</code>
 */
class PublicKey extends \Google\Protobuf\Internal\Message
{
    /**
     * DER-encoded public key, encoding method is specified by the
     * key_details attribute.
     *
     * Generated from protobuf field <code>optional bytes raw_bytes = 1;</code>
     */
    protected $raw_bytes = null;
    /**
     * Key encoding and signature algorithm to use for this key.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKeyDetails key_details = 2;</code>
     */
    protected $key_details = 0;
    /**
     * Optional validity period for this key, *inclusive* of the endpoints.
     *
     * Generated from protobuf field <code>optional .dev.sigstore.common.v1.TimeRange valid_for = 3;</code>
     */
    protected $valid_for = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $raw_bytes
     *           DER-encoded public key, encoding method is specified by the
     *           key_details attribute.
     *     @type int $key_details
     *           Key encoding and signature algorithm to use for this key.
     *     @type \Dev\Sigstore\Common\V1\TimeRange $valid_for
     *           Optional validity period for this key, *inclusive* of the endpoints.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * DER-encoded public key, encoding method is specified by the
     * key_details attribute.
     *
     * Generated from protobuf field <code>optional bytes raw_bytes = 1;</code>
     * @return string
     */
    public function getRawBytes()
    {
        return isset($this->raw_bytes) ? $this->raw_bytes : '';
    }

    public function hasRawBytes()
    {
        return isset($this->raw_bytes);
    }

    public function clearRawBytes()
    {
        unset($this->raw_bytes);
    }

    /**
     * DER-encoded public key, encoding method is specified by the
     * key_details attribute.
     *
     * Generated from protobuf field <code>optional bytes raw_bytes = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRawBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->raw_bytes = $var;

        return $this;
    }

    /**
     * Key encoding and signature algorithm to use for this key.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKeyDetails key_details = 2;</code>
     * @return int
     */
    public function getKeyDetails()
    {
        return $this->key_details;
    }

    /**
     * Key encoding and signature algorithm to use for this key.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKeyDetails key_details = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKeyDetails($var)
    {
        GPBUtil::checkEnum($var, \Dev\Sigstore\Common\V1\PublicKeyDetails::class);
        $this->key_details = $var;

        return $this;
    }

    /**
     * Optional validity period for this key, *inclusive* of the endpoints.
     *
     * Generated from protobuf field <code>optional .dev.sigstore.common.v1.TimeRange valid_for = 3;</code>
     * @return \Dev\Sigstore\Common\V1\TimeRange|null
     */
    public function getValidFor()
    {
        return $this->valid_for;
    }

    public function hasValidFor()
    {
        return isset($this->valid_for);
    }

    public function clearValidFor()
    {
        unset($this->valid_for);
    }

    /**
     * Optional validity period for this key, *inclusive* of the endpoints.
     *
     * Generated from protobuf field <code>optional .dev.sigstore.common.v1.TimeRange valid_for = 3;</code>
     * @param \Dev\Sigstore\Common\V1\TimeRange $var
     * @return $this
     */
    public function setValidFor($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\TimeRange::class);
        $this->valid_for = $var;

        return $this;
    }

}

