<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use UnexpectedValueException;

/**
 * Details of a specific public key, capturing the the key encoding method,
 * and signature algorithm.
 * PublicKeyDetails captures the public key/hash algorithm combinations
 * recommended in the Sigstore ecosystem.
 * This is modelled as a linear set as we want to provide a small number of
 * opinionated options instead of allowing every possible permutation.
 * Any changes to this enum MUST be reflected in the algorithm registry.
 * See: <https://github.com/sigstore/architecture-docs/blob/main/algorithm-registry.md>
 * To avoid the possibility of contradicting formats such as PKCS1 with
 * ED25519 the valid permutations are listed as a linear set instead of a
 * cartesian set (i.e one combined variable instead of two, one for encoding
 * and one for the signature algorithm).
 *
 * Protobuf type <code>dev.sigstore.common.v1.PublicKeyDetails</code>
 */
class PublicKeyDetails
{
    /**
     * Generated from protobuf enum <code>PUBLIC_KEY_DETAILS_UNSPECIFIED = 0;</code>
     */
    const PUBLIC_KEY_DETAILS_UNSPECIFIED = 0;
    /**
     * RSA
     *
     * Generated from protobuf enum <code>PKCS1_RSA_PKCS1V5 = 1 [deprecated = true];</code>
     */
    const PKCS1_RSA_PKCS1V5 = 1;
    /**
     * See RFC8017
     *
     * Generated from protobuf enum <code>PKCS1_RSA_PSS = 2 [deprecated = true];</code>
     */
    const PKCS1_RSA_PSS = 2;
    /**
     * Generated from protobuf enum <code>PKIX_RSA_PKCS1V5 = 3 [deprecated = true];</code>
     */
    const PKIX_RSA_PKCS1V5 = 3;
    /**
     * Generated from protobuf enum <code>PKIX_RSA_PSS = 4 [deprecated = true];</code>
     */
    const PKIX_RSA_PSS = 4;
    /**
     * RSA public key in PKIX format, PKCS#1v1.5 signature
     *
     * Generated from protobuf enum <code>PKIX_RSA_PKCS1V15_2048_SHA256 = 9;</code>
     */
    const PKIX_RSA_PKCS1V15_2048_SHA256 = 9;
    /**
     * Generated from protobuf enum <code>PKIX_RSA_PKCS1V15_3072_SHA256 = 10;</code>
     */
    const PKIX_RSA_PKCS1V15_3072_SHA256 = 10;
    /**
     * Generated from protobuf enum <code>PKIX_RSA_PKCS1V15_4096_SHA256 = 11;</code>
     */
    const PKIX_RSA_PKCS1V15_4096_SHA256 = 11;
    /**
     * RSA public key in PKIX format, RSASSA-PSS signature
     *
     * Generated from protobuf enum <code>PKIX_RSA_PSS_2048_SHA256 = 16;</code>
     */
    const PKIX_RSA_PSS_2048_SHA256 = 16;
    /**
     * Generated from protobuf enum <code>PKIX_RSA_PSS_3072_SHA256 = 17;</code>
     */
    const PKIX_RSA_PSS_3072_SHA256 = 17;
    /**
     * Generated from protobuf enum <code>PKIX_RSA_PSS_4096_SHA256 = 18;</code>
     */
    const PKIX_RSA_PSS_4096_SHA256 = 18;
    /**
     * ECDSA
     *
     * Generated from protobuf enum <code>PKIX_ECDSA_P256_HMAC_SHA_256 = 6 [deprecated = true];</code>
     */
    const PKIX_ECDSA_P256_HMAC_SHA_256 = 6;
    /**
     * See NIST FIPS 186-4
     *
     * Generated from protobuf enum <code>PKIX_ECDSA_P256_SHA_256 = 5;</code>
     */
    const PKIX_ECDSA_P256_SHA_256 = 5;
    /**
     * Generated from protobuf enum <code>PKIX_ECDSA_P384_SHA_384 = 12;</code>
     */
    const PKIX_ECDSA_P384_SHA_384 = 12;
    /**
     * Generated from protobuf enum <code>PKIX_ECDSA_P521_SHA_512 = 13;</code>
     */
    const PKIX_ECDSA_P521_SHA_512 = 13;
    /**
     * Ed 25519
     *
     * Generated from protobuf enum <code>PKIX_ED25519 = 7;</code>
     */
    const PKIX_ED25519 = 7;
    /**
     * Generated from protobuf enum <code>PKIX_ED25519_PH = 8;</code>
     */
    const PKIX_ED25519_PH = 8;
    /**
     * These algorithms are deprecated and should not be used, but they
     * were/are being used by most Sigstore clients implementations.
     *
     * Generated from protobuf enum <code>PKIX_ECDSA_P384_SHA_256 = 19 [deprecated = true];</code>
     */
    const PKIX_ECDSA_P384_SHA_256 = 19;
    /**
     * Generated from protobuf enum <code>PKIX_ECDSA_P521_SHA_256 = 20 [deprecated = true];</code>
     */
    const PKIX_ECDSA_P521_SHA_256 = 20;
    /**
     * LMS and LM-OTS
     * 
     * These algorithms are deprecated and should not be used.
     * Keys and signatures MAY be used by private Sigstore
     * deployments, but will not be supported by the public
     * good instance.
     * USER WARNING: LMS and LM-OTS are both stateful signature schemes.
     * Using them correctly requires discretion and careful consideration
     * to ensure that individual secret keys are not used more than once.
     * In addition, LM-OTS is a single-use scheme, meaning that it
     * MUST NOT be used for more than one signature per LM-OTS key.
     * If you cannot maintain these invariants, you MUST NOT use these
     * schemes.
     *
     * Generated from protobuf enum <code>LMS_SHA256 = 14 [deprecated = true];</code>
     */
    const LMS_SHA256 = 14;
    /**
     * Generated from protobuf enum <code>LMOTS_SHA256 = 15 [deprecated = true];</code>
     */
    const LMOTS_SHA256 = 15;
    /**
     * ML-DSA
     * These ML_DSA_65 and ML-DSA_87 algorithms are the pure variants that
     * take data to sign rather than the prehash variants (HashML-DSA), which
     * take digests.  While considered quantum-resistant, their usage
     * involves tradeoffs in that signatures and keys are much larger, and
     * this makes deployments more costly.
     * USER WARNING: ML_DSA_65 and ML_DSA_87 are experimental algorithms.  
     * In the future they MAY be used by private Sigstore deployments, but
     * they are not yet fully functional.  This warning will be removed when 
     * these algorithms are widely supported by Sigstore clients and servers, 
     * but care should still be taken for production environments.
     *
     * Generated from protobuf enum <code>ML_DSA_65 = 21;</code>
     */
    const ML_DSA_65 = 21;
    /**
     * Generated from protobuf enum <code>ML_DSA_87 = 22;</code>
     */
    const ML_DSA_87 = 22;

    private static $valueToName = [
        self::PUBLIC_KEY_DETAILS_UNSPECIFIED => 'PUBLIC_KEY_DETAILS_UNSPECIFIED',
        self::PKCS1_RSA_PKCS1V5 => 'PKCS1_RSA_PKCS1V5',
        self::PKCS1_RSA_PSS => 'PKCS1_RSA_PSS',
        self::PKIX_RSA_PKCS1V5 => 'PKIX_RSA_PKCS1V5',
        self::PKIX_RSA_PSS => 'PKIX_RSA_PSS',
        self::PKIX_RSA_PKCS1V15_2048_SHA256 => 'PKIX_RSA_PKCS1V15_2048_SHA256',
        self::PKIX_RSA_PKCS1V15_3072_SHA256 => 'PKIX_RSA_PKCS1V15_3072_SHA256',
        self::PKIX_RSA_PKCS1V15_4096_SHA256 => 'PKIX_RSA_PKCS1V15_4096_SHA256',
        self::PKIX_RSA_PSS_2048_SHA256 => 'PKIX_RSA_PSS_2048_SHA256',
        self::PKIX_RSA_PSS_3072_SHA256 => 'PKIX_RSA_PSS_3072_SHA256',
        self::PKIX_RSA_PSS_4096_SHA256 => 'PKIX_RSA_PSS_4096_SHA256',
        self::PKIX_ECDSA_P256_HMAC_SHA_256 => 'PKIX_ECDSA_P256_HMAC_SHA_256',
        self::PKIX_ECDSA_P256_SHA_256 => 'PKIX_ECDSA_P256_SHA_256',
        self::PKIX_ECDSA_P384_SHA_384 => 'PKIX_ECDSA_P384_SHA_384',
        self::PKIX_ECDSA_P521_SHA_512 => 'PKIX_ECDSA_P521_SHA_512',
        self::PKIX_ED25519 => 'PKIX_ED25519',
        self::PKIX_ED25519_PH => 'PKIX_ED25519_PH',
        self::PKIX_ECDSA_P384_SHA_256 => 'PKIX_ECDSA_P384_SHA_256',
        self::PKIX_ECDSA_P521_SHA_256 => 'PKIX_ECDSA_P521_SHA_256',
        self::LMS_SHA256 => 'LMS_SHA256',
        self::LMOTS_SHA256 => 'LMOTS_SHA256',
        self::ML_DSA_65 => 'ML_DSA_65',
        self::ML_DSA_87 => 'ML_DSA_87',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

