<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This message holds a RFC 3161 timestamp.
 *
 * Generated from protobuf message <code>dev.sigstore.common.v1.RFC3161SignedTimestamp</code>
 */
class RFC3161SignedTimestamp extends \Google\Protobuf\Internal\Message
{
    /**
     * Signed timestamp is the DER encoded TimeStampResponse.
     * See https://www.rfc-editor.org/rfc/rfc3161.html#section-2.4.2
     *
     * Generated from protobuf field <code>bytes signed_timestamp = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $signed_timestamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signed_timestamp
     *           Signed timestamp is the DER encoded TimeStampResponse.
     *           See https://www.rfc-editor.org/rfc/rfc3161.html#section-2.4.2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Signed timestamp is the DER encoded TimeStampResponse.
     * See https://www.rfc-editor.org/rfc/rfc3161.html#section-2.4.2
     *
     * Generated from protobuf field <code>bytes signed_timestamp = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getSignedTimestamp()
    {
        return $this->signed_timestamp;
    }

    /**
     * Signed timestamp is the DER encoded TimeStampResponse.
     * See https://www.rfc-editor.org/rfc/rfc3161.html#section-2.4.2
     *
     * Generated from protobuf field <code>bytes signed_timestamp = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setSignedTimestamp($var)
    {
        GPBUtil::checkString($var, False);
        $this->signed_timestamp = $var;

        return $this;
    }

}

