<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>dev.sigstore.common.v1.SubjectAlternativeNameType</code>
 */
class SubjectAlternativeNameType
{
    /**
     * Generated from protobuf enum <code>SUBJECT_ALTERNATIVE_NAME_TYPE_UNSPECIFIED = 0;</code>
     */
    const SUBJECT_ALTERNATIVE_NAME_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>EMAIL = 1;</code>
     */
    const EMAIL = 1;
    /**
     * Generated from protobuf enum <code>URI = 2;</code>
     */
    const URI = 2;
    /**
     * OID 1.3.6.1.4.1.57264.1.7
     * See https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md#1361415726417--othername-san
     * for more details.
     *
     * Generated from protobuf enum <code>OTHER_NAME = 3;</code>
     */
    const OTHER_NAME = 3;

    private static $valueToName = [
        self::SUBJECT_ALTERNATIVE_NAME_TYPE_UNSPECIFIED => 'SUBJECT_ALTERNATIVE_NAME_TYPE_UNSPECIFIED',
        self::EMAIL => 'EMAIL',
        self::URI => 'URI',
        self::OTHER_NAME => 'OTHER_NAME',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

