<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.common.v1.SubjectAlternativeName</code>
 */
class SubjectAlternativeName extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.SubjectAlternativeNameType type = 1;</code>
     */
    protected $type = 0;
    protected $identity;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $regexp
     *           A regular expression describing the expected value for
     *           the SAN.
     *     @type string $value
     *           The exact value to match against.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.SubjectAlternativeNameType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.SubjectAlternativeNameType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Dev\Sigstore\Common\V1\SubjectAlternativeNameType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * A regular expression describing the expected value for
     * the SAN.
     *
     * Generated from protobuf field <code>string regexp = 2;</code>
     * @return string
     */
    public function getRegexp()
    {
        return $this->readOneof(2);
    }

    public function hasRegexp()
    {
        return $this->hasOneof(2);
    }

    /**
     * A regular expression describing the expected value for
     * the SAN.
     *
     * Generated from protobuf field <code>string regexp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRegexp($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * The exact value to match against.
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->readOneof(3);
    }

    public function hasValue()
    {
        return $this->hasOneof(3);
    }

    /**
     * The exact value to match against.
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getIdentity()
    {
        return $this->whichOneof("identity");
    }

}

