<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.common.v1.X509Certificate</code>
 */
class X509Certificate extends \Google\Protobuf\Internal\Message
{
    /**
     * DER-encoded X.509 certificate.
     *
     * Generated from protobuf field <code>bytes raw_bytes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $raw_bytes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $raw_bytes
     *           DER-encoded X.509 certificate.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * DER-encoded X.509 certificate.
     *
     * Generated from protobuf field <code>bytes raw_bytes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getRawBytes()
    {
        return $this->raw_bytes;
    }

    /**
     * DER-encoded X.509 certificate.
     *
     * Generated from protobuf field <code>bytes raw_bytes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setRawBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->raw_bytes = $var;

        return $this;
    }

}

