<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_common.proto

namespace Dev\Sigstore\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A collection of X.509 certificates.
 * This "chain" can be used in multiple contexts, such as providing a root CA
 * certificate within a TUF root of trust or multiple untrusted certificates for
 * the purpose of chain building.
 *
 * Generated from protobuf message <code>dev.sigstore.common.v1.X509CertificateChain</code>
 */
class X509CertificateChain extends \Google\Protobuf\Internal\Message
{
    /**
     * One or more DER-encoded certificates.
     * In some contexts (such as `VerificationMaterial.x509_certificate_chain`), this sequence
     * has an imposed order. Unless explicitly specified, there is otherwise no
     * guaranteed order.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.X509Certificate certificates = 1;</code>
     */
    private $certificates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Dev\Sigstore\Common\V1\X509Certificate>|\Google\Protobuf\Internal\RepeatedField $certificates
     *           One or more DER-encoded certificates.
     *           In some contexts (such as `VerificationMaterial.x509_certificate_chain`), this sequence
     *           has an imposed order. Unless explicitly specified, there is otherwise no
     *           guaranteed order.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * One or more DER-encoded certificates.
     * In some contexts (such as `VerificationMaterial.x509_certificate_chain`), this sequence
     * has an imposed order. Unless explicitly specified, there is otherwise no
     * guaranteed order.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.X509Certificate certificates = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificates()
    {
        return $this->certificates;
    }

    /**
     * One or more DER-encoded certificates.
     * In some contexts (such as `VerificationMaterial.x509_certificate_chain`), this sequence
     * has an imposed order. Unless explicitly specified, there is otherwise no
     * guaranteed order.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.X509Certificate certificates = 1;</code>
     * @param array<\Dev\Sigstore\Common\V1\X509Certificate>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Common\V1\X509Certificate::class);
        $this->certificates = $arr;

        return $this;
    }

}

