<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

namespace Io\Intoto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An authenticated message of arbitrary type.
 *
 * Generated from protobuf message <code>io.intoto.Envelope</code>
 */
class Envelope extends \Google\Protobuf\Internal\Message
{
    /**
     * Message to be signed. (In JSON, this is encoded as base64.)
     * REQUIRED.
     *
     * Generated from protobuf field <code>bytes payload = 1;</code>
     */
    protected $payload = '';
    /**
     * String unambiguously identifying how to interpret payload.
     * REQUIRED.
     *
     * Generated from protobuf field <code>string payloadType = 2;</code>
     */
    protected $payloadType = '';
    /**
     * Signature over:
     *     PAE(type, payload)
     * Where PAE is defined as:
     * PAE(type, payload) = "DSSEv1" + SP + LEN(type) + SP + type + SP + LEN(payload) + SP + payload
     * +               = concatenation
     * SP              = ASCII space [0x20]
     * "DSSEv1"        = ASCII [0x44, 0x53, 0x53, 0x45, 0x76, 0x31]
     * LEN(s)          = ASCII decimal encoding of the byte length of s, with no leading zeros
     * REQUIRED (length >= 1).
     *
     * Generated from protobuf field <code>repeated .io.intoto.Signature signatures = 3;</code>
     */
    private $signatures;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payload
     *           Message to be signed. (In JSON, this is encoded as base64.)
     *           REQUIRED.
     *     @type string $payloadType
     *           String unambiguously identifying how to interpret payload.
     *           REQUIRED.
     *     @type array<\Io\Intoto\Signature>|\Google\Protobuf\Internal\RepeatedField $signatures
     *           Signature over:
     *               PAE(type, payload)
     *           Where PAE is defined as:
     *           PAE(type, payload) = "DSSEv1" + SP + LEN(type) + SP + type + SP + LEN(payload) + SP + payload
     *           +               = concatenation
     *           SP              = ASCII space [0x20]
     *           "DSSEv1"        = ASCII [0x44, 0x53, 0x53, 0x45, 0x76, 0x31]
     *           LEN(s)          = ASCII decimal encoding of the byte length of s, with no leading zeros
     *           REQUIRED (length >= 1).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Envelope::initOnce();
        parent::__construct($data);
    }

    /**
     * Message to be signed. (In JSON, this is encoded as base64.)
     * REQUIRED.
     *
     * Generated from protobuf field <code>bytes payload = 1;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Message to be signed. (In JSON, this is encoded as base64.)
     * REQUIRED.
     *
     * Generated from protobuf field <code>bytes payload = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

    /**
     * String unambiguously identifying how to interpret payload.
     * REQUIRED.
     *
     * Generated from protobuf field <code>string payloadType = 2;</code>
     * @return string
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * String unambiguously identifying how to interpret payload.
     * REQUIRED.
     *
     * Generated from protobuf field <code>string payloadType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkString($var, True);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Signature over:
     *     PAE(type, payload)
     * Where PAE is defined as:
     * PAE(type, payload) = "DSSEv1" + SP + LEN(type) + SP + type + SP + LEN(payload) + SP + payload
     * +               = concatenation
     * SP              = ASCII space [0x20]
     * "DSSEv1"        = ASCII [0x44, 0x53, 0x53, 0x45, 0x76, 0x31]
     * LEN(s)          = ASCII decimal encoding of the byte length of s, with no leading zeros
     * REQUIRED (length >= 1).
     *
     * Generated from protobuf field <code>repeated .io.intoto.Signature signatures = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatures()
    {
        return $this->signatures;
    }

    /**
     * Signature over:
     *     PAE(type, payload)
     * Where PAE is defined as:
     * PAE(type, payload) = "DSSEv1" + SP + LEN(type) + SP + type + SP + LEN(payload) + SP + payload
     * +               = concatenation
     * SP              = ASCII space [0x20]
     * "DSSEv1"        = ASCII [0x44, 0x53, 0x53, 0x45, 0x76, 0x31]
     * LEN(s)          = ASCII decimal encoding of the byte length of s, with no leading zeros
     * REQUIRED (length >= 1).
     *
     * Generated from protobuf field <code>repeated .io.intoto.Signature signatures = 3;</code>
     * @param array<\Io\Intoto\Signature>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Intoto\Signature::class);
        $this->signatures = $arr;

        return $this;
    }

}

