<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

namespace Io\Intoto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.intoto.Signature</code>
 */
class Signature extends \Google\Protobuf\Internal\Message
{
    /**
     * Signature itself. (In JSON, this is encoded as base64.)
     * REQUIRED.
     *
     * Generated from protobuf field <code>bytes sig = 1;</code>
     */
    protected $sig = '';
    /**
     * *Unauthenticated* hint identifying which public key was used.
     * OPTIONAL.
     *
     * Generated from protobuf field <code>string keyid = 2;</code>
     */
    protected $keyid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sig
     *           Signature itself. (In JSON, this is encoded as base64.)
     *           REQUIRED.
     *     @type string $keyid
     *           *Unauthenticated* hint identifying which public key was used.
     *           OPTIONAL.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Envelope::initOnce();
        parent::__construct($data);
    }

    /**
     * Signature itself. (In JSON, this is encoded as base64.)
     * REQUIRED.
     *
     * Generated from protobuf field <code>bytes sig = 1;</code>
     * @return string
     */
    public function getSig()
    {
        return $this->sig;
    }

    /**
     * Signature itself. (In JSON, this is encoded as base64.)
     * REQUIRED.
     *
     * Generated from protobuf field <code>bytes sig = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSig($var)
    {
        GPBUtil::checkString($var, False);
        $this->sig = $var;

        return $this;
    }

    /**
     * *Unauthenticated* hint identifying which public key was used.
     * OPTIONAL.
     *
     * Generated from protobuf field <code>string keyid = 2;</code>
     * @return string
     */
    public function getKeyid()
    {
        return $this->keyid;
    }

    /**
     * *Unauthenticated* hint identifying which public key was used.
     * OPTIONAL.
     *
     * Generated from protobuf field <code>string keyid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyid($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyid = $var;

        return $this;
    }

}

