<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

namespace GPBMetadata;

class Envelope
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xEE\x01\x0A\x0Eenvelope.proto\x12\x09io.intoto\"Z\x0A\x08Envelope\x12\x0F\x0A\x07payload\x18\x01 \x01(\x0C\x12\x13\x0A\x0BpayloadType\x18\x02 \x01(\x09\x12(\x0A\x0Asignatures\x18\x03 \x03(\x0B2\x14.io.intoto.Signature\"'\x0A\x09Signature\x12\x0B\x0A\x03sig\x18\x01 \x01(\x0C\x12\x0D\x0A\x05keyid\x18\x02 \x01(\x09BDZ1github.com/sigstore/protobuf-specs/gen/pb-go/dsse\xEA\x02\x0ESigstore::DSSEb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

