<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace GPBMetadata;

class Events
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC0\x06\x0A\x0Cevents.proto\x12\x16dev.sigstore.events.v1\x1A\x1Fgoogle/protobuf/timestamp.proto\"\xBA\x04\x0A\x0ACloudEvent\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0E\x0A\x06source\x18\x02 \x01(\x09\x12\x14\x0A\x0Cspec_version\x18\x03 \x01(\x09\x12\x0C\x0A\x04type\x18\x04 \x01(\x09\x12F\x0A\x0Aattributes\x18\x05 \x03(\x0B22.dev.sigstore.events.v1.CloudEvent.AttributesEntry\x12\x15\x0A\x0Bbinary_data\x18\x06 \x01(\x0CH\x00\x12\x13\x0A\x09text_data\x18\x07 \x01(\x09H\x00\x12*\x0A\x0Aproto_data\x18\x08 \x01(\x0B2\x14.google.protobuf.AnyH\x00\x1An\x0A\x0FAttributesEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12J\x0A\x05value\x18\x02 \x01(\x0B2;.dev.sigstore.events.v1.CloudEvent.CloudEventAttributeValue:\x028\x01\x1A\xD3\x01\x0A\x18CloudEventAttributeValue\x12\x14\x0A\x0Ace_boolean\x18\x01 \x01(\x08H\x00\x12\x14\x0A\x0Ace_integer\x18\x02 \x01(\x05H\x00\x12\x13\x0A\x09ce_string\x18\x03 \x01(\x09H\x00\x12\x12\x0A\x08ce_bytes\x18\x04 \x01(\x0CH\x00\x12\x10\x0A\x06ce_uri\x18\x05 \x01(\x09H\x00\x12\x14\x0A\x0Ace_uri_ref\x18\x06 \x01(\x09H\x00\x122\x0A\x0Cce_timestamp\x18\x07 \x01(\x0B2\x1A.google.protobuf.TimestampH\x00B\x06\x0A\x04attrB\x06\x0A\x04data\"E\x0A\x0FCloudEventBatch\x122\x0A\x06events\x18\x01 \x03(\x0B2\".dev.sigstore.events.v1.CloudEventBk\x0A\x1Cdev.sigstore.proto.events.v1P\x01Z6github.com/sigstore/protobuf-specs/gen/pb-go/events/v1\xEA\x02\x10Sigstore::Eventsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

