<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_rekor.proto

namespace GPBMetadata;

class SigstoreRekor
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\SigstoreCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEF\x06\x0A\x14sigstore_rekor.proto\x12\x15dev.sigstore.rekor.v1\x1A\x15sigstore_common.proto\"6\x0A\x0BKindVersion\x12\x11\x0A\x04kind\x18\x01 \x01(\x09B\x03\xE0A\x02\x12\x14\x0A\x07version\x18\x02 \x01(\x09B\x03\xE0A\x02\"#\x0A\x0ACheckpoint\x12\x15\x0A\x08envelope\x18\x01 \x01(\x09B\x03\xE0A\x02\"\xA9\x01\x0A\x0EInclusionProof\x12\x16\x0A\x09log_index\x18\x01 \x01(\x03B\x03\xE0A\x02\x12\x16\x0A\x09root_hash\x18\x02 \x01(\x0CB\x03\xE0A\x02\x12\x16\x0A\x09tree_size\x18\x03 \x01(\x03B\x03\xE0A\x02\x12\x13\x0A\x06hashes\x18\x04 \x03(\x0CB\x03\xE0A\x02\x12:\x0A\x0Acheckpoint\x18\x05 \x01(\x0B2!.dev.sigstore.rekor.v1.CheckpointB\x03\xE0A\x02\"7\x0A\x10InclusionPromise\x12#\x0A\x16signed_entry_timestamp\x18\x01 \x01(\x0CB\x03\xE0A\x02\"\xE4\x02\x0A\x14TransparencyLogEntry\x12\x16\x0A\x09log_index\x18\x01 \x01(\x03B\x03\xE0A\x02\x122\x0A\x06log_id\x18\x02 \x01(\x0B2\x1D.dev.sigstore.common.v1.LogIdB\x03\xE0A\x02\x12=\x0A\x0Ckind_version\x18\x03 \x01(\x0B2\".dev.sigstore.rekor.v1.KindVersionB\x03\xE0A\x02\x12\x1C\x0A\x0Fintegrated_time\x18\x04 \x01(\x03B\x03\xE0A\x02\x12B\x0A\x11inclusion_promise\x18\x05 \x01(\x0B2'.dev.sigstore.rekor.v1.InclusionPromise\x12C\x0A\x0Finclusion_proof\x18\x06 \x01(\x0B2%.dev.sigstore.rekor.v1.InclusionProofB\x03\xE0A\x02\x12\x1A\x0A\x12canonicalized_body\x18\x07 \x01(\x0CBx\x0A\x1Bdev.sigstore.proto.rekor.v1B\x0ARekorProtoP\x01Z5github.com/sigstore/protobuf-specs/gen/pb-go/rekor/v1\xEA\x02\x13Sigstore::Rekor::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

