<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_bundle.proto

namespace GPBMetadata;

class SigstoreBundle
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Envelope::initOnce();
        \GPBMetadata\SigstoreCommon::initOnce();
        \GPBMetadata\SigstoreRekor::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xFD\x07\x0A\x15sigstore_bundle.proto\x12\x16dev.sigstore.bundle.v1\x1A\x0Eenvelope.proto\x1A\x15sigstore_common.proto\x1A\x14sigstore_rekor.proto\"g\x0A\x19TimestampVerificationData\x12J\x0A\x12rfc3161_timestamps\x18\x01 \x03(\x0B2..dev.sigstore.common.v1.RFC3161SignedTimestamp\"\x9E\x03\x0A\x14VerificationMaterial\x12F\x0A\x0Apublic_key\x18\x01 \x01(\x0B2+.dev.sigstore.common.v1.PublicKeyIdentifierB\x03\xE0A\x02H\x00\x12S\x0A\x16x509_certificate_chain\x18\x02 \x01(\x0B2,.dev.sigstore.common.v1.X509CertificateChainB\x03\xE0A\x02H\x00\x12C\x0A\x0Bcertificate\x18\x05 \x01(\x0B2'.dev.sigstore.common.v1.X509CertificateB\x03\xE0A\x02H\x00\x12A\x0A\x0Ctlog_entries\x18\x03 \x03(\x0B2+.dev.sigstore.rekor.v1.TransparencyLogEntry\x12V\x0A\x1Btimestamp_verification_data\x18\x04 \x01(\x0B21.dev.sigstore.bundle.v1.TimestampVerificationDataB\x09\x0A\x07content\"\xFE\x01\x0A\x06Bundle\x12\x12\x0A\x0Amedia_type\x18\x01 \x01(\x09\x12P\x0A\x15verification_material\x18\x02 \x01(\x0B2,.dev.sigstore.bundle.v1.VerificationMaterialB\x03\xE0A\x02\x12J\x0A\x11message_signature\x18\x03 \x01(\x0B2(.dev.sigstore.common.v1.MessageSignatureB\x03\xE0A\x02H\x00\x121\x0A\x0Ddsse_envelope\x18\x04 \x01(\x0B2\x13.io.intoto.EnvelopeB\x03\xE0A\x02H\x00B\x09\x0A\x07contentJ\x04\x08\x05\x103B|\x0A\x1Cdev.sigstore.proto.bundle.v1B\x0BBundleProtoP\x01Z6github.com/sigstore/protobuf-specs/gen/pb-go/bundle/v1\xEA\x02\x14Sigstore::Bundle::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

