<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Dev\Sigstore\Events\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.events.v1.CloudEventBatch</code>
 */
class CloudEventBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.events.v1.CloudEvent events = 1;</code>
     */
    private $events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Dev\Sigstore\Events\V1\CloudEvent>|\Google\Protobuf\Internal\RepeatedField $events
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.events.v1.CloudEvent events = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.events.v1.CloudEvent events = 1;</code>
     * @param array<\Dev\Sigstore\Events\V1\CloudEvent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Events\V1\CloudEvent::class);
        $this->events = $arr;

        return $this;
    }

}

