<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A light-weight set of options/policies for identifying trusted signers,
 * used during verification of a single artifact.
 *
 * Generated from protobuf message <code>dev.sigstore.verification.v1.ArtifactVerificationOptions</code>
 */
class ArtifactVerificationOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional options for artifact transparency log verification.
     * If none is provided, the default verification options are:
     * Threshold: 1
     * Online verification: false
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TlogOptions tlog_options = 3;</code>
     */
    protected $tlog_options = null;
    /**
     * Optional options for certificate transparency log verification.
     * If none is provided, the default verification options are:
     * Threshold: 1
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.CtlogOptions ctlog_options = 4;</code>
     */
    protected $ctlog_options = null;
    /**
     * Optional options for certificate signed timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold: 0
     * Disable: true
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TimestampAuthorityOptions tsa_options = 5;</code>
     */
    protected $tsa_options = null;
    /**
     * Optional options for integrated timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold: 0
     * Disable: true
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TlogIntegratedTimestampOptions integrated_ts_options = 6;</code>
     */
    protected $integrated_ts_options = null;
    /**
     * Optional options for observed timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold 1
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.ObserverTimestampOptions observer_options = 7;</code>
     */
    protected $observer_options = null;
    protected $signers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Dev\Sigstore\Verification\V1\CertificateIdentities $certificate_identities
     *     @type \Dev\Sigstore\Verification\V1\PublicKeyIdentities $public_keys
     *           To simplify verification implementation, the logic for
     *           bundle verification should be implemented as a
     *           higher-order function, where one of argument should be an
     *           interface over the set of trusted public keys, like this:
     *           `Verify(bytes artifact, bytes signature, string key_id)`.
     *           This way the caller is in full control of mapping the
     *           identified (or hinted) key in the bundle to one of the
     *           trusted keys, as this process is inherently application
     *           specific.
     *     @type \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogOptions $tlog_options
     *           Optional options for artifact transparency log verification.
     *           If none is provided, the default verification options are:
     *           Threshold: 1
     *           Online verification: false
     *           Disable: false
     *     @type \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\CtlogOptions $ctlog_options
     *           Optional options for certificate transparency log verification.
     *           If none is provided, the default verification options are:
     *           Threshold: 1
     *           Disable: false
     *     @type \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TimestampAuthorityOptions $tsa_options
     *           Optional options for certificate signed timestamp verification.
     *           If none is provided, the default verification options are:
     *           Threshold: 0
     *           Disable: true
     *     @type \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogIntegratedTimestampOptions $integrated_ts_options
     *           Optional options for integrated timestamp verification.
     *           If none is provided, the default verification options are:
     *           Threshold: 0
     *           Disable: true
     *     @type \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\ObserverTimestampOptions $observer_options
     *           Optional options for observed timestamp verification.
     *           If none is provided, the default verification options are:
     *           Threshold 1
     *           Disable: false
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.verification.v1.CertificateIdentities certificate_identities = 1;</code>
     * @return \Dev\Sigstore\Verification\V1\CertificateIdentities|null
     */
    public function getCertificateIdentities()
    {
        return $this->readOneof(1);
    }

    public function hasCertificateIdentities()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.verification.v1.CertificateIdentities certificate_identities = 1;</code>
     * @param \Dev\Sigstore\Verification\V1\CertificateIdentities $var
     * @return $this
     */
    public function setCertificateIdentities($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\CertificateIdentities::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * To simplify verification implementation, the logic for
     * bundle verification should be implemented as a
     * higher-order function, where one of argument should be an
     * interface over the set of trusted public keys, like this:
     * `Verify(bytes artifact, bytes signature, string key_id)`.
     * This way the caller is in full control of mapping the
     * identified (or hinted) key in the bundle to one of the
     * trusted keys, as this process is inherently application
     * specific.
     *
     * Generated from protobuf field <code>.dev.sigstore.verification.v1.PublicKeyIdentities public_keys = 2;</code>
     * @return \Dev\Sigstore\Verification\V1\PublicKeyIdentities|null
     */
    public function getPublicKeys()
    {
        return $this->readOneof(2);
    }

    public function hasPublicKeys()
    {
        return $this->hasOneof(2);
    }

    /**
     * To simplify verification implementation, the logic for
     * bundle verification should be implemented as a
     * higher-order function, where one of argument should be an
     * interface over the set of trusted public keys, like this:
     * `Verify(bytes artifact, bytes signature, string key_id)`.
     * This way the caller is in full control of mapping the
     * identified (or hinted) key in the bundle to one of the
     * trusted keys, as this process is inherently application
     * specific.
     *
     * Generated from protobuf field <code>.dev.sigstore.verification.v1.PublicKeyIdentities public_keys = 2;</code>
     * @param \Dev\Sigstore\Verification\V1\PublicKeyIdentities $var
     * @return $this
     */
    public function setPublicKeys($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\PublicKeyIdentities::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Optional options for artifact transparency log verification.
     * If none is provided, the default verification options are:
     * Threshold: 1
     * Online verification: false
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TlogOptions tlog_options = 3;</code>
     * @return \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogOptions|null
     */
    public function getTlogOptions()
    {
        return $this->tlog_options;
    }

    public function hasTlogOptions()
    {
        return isset($this->tlog_options);
    }

    public function clearTlogOptions()
    {
        unset($this->tlog_options);
    }

    /**
     * Optional options for artifact transparency log verification.
     * If none is provided, the default verification options are:
     * Threshold: 1
     * Online verification: false
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TlogOptions tlog_options = 3;</code>
     * @param \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogOptions $var
     * @return $this
     */
    public function setTlogOptions($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogOptions::class);
        $this->tlog_options = $var;

        return $this;
    }

    /**
     * Optional options for certificate transparency log verification.
     * If none is provided, the default verification options are:
     * Threshold: 1
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.CtlogOptions ctlog_options = 4;</code>
     * @return \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\CtlogOptions|null
     */
    public function getCtlogOptions()
    {
        return $this->ctlog_options;
    }

    public function hasCtlogOptions()
    {
        return isset($this->ctlog_options);
    }

    public function clearCtlogOptions()
    {
        unset($this->ctlog_options);
    }

    /**
     * Optional options for certificate transparency log verification.
     * If none is provided, the default verification options are:
     * Threshold: 1
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.CtlogOptions ctlog_options = 4;</code>
     * @param \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\CtlogOptions $var
     * @return $this
     */
    public function setCtlogOptions($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\CtlogOptions::class);
        $this->ctlog_options = $var;

        return $this;
    }

    /**
     * Optional options for certificate signed timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold: 0
     * Disable: true
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TimestampAuthorityOptions tsa_options = 5;</code>
     * @return \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TimestampAuthorityOptions|null
     */
    public function getTsaOptions()
    {
        return $this->tsa_options;
    }

    public function hasTsaOptions()
    {
        return isset($this->tsa_options);
    }

    public function clearTsaOptions()
    {
        unset($this->tsa_options);
    }

    /**
     * Optional options for certificate signed timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold: 0
     * Disable: true
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TimestampAuthorityOptions tsa_options = 5;</code>
     * @param \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TimestampAuthorityOptions $var
     * @return $this
     */
    public function setTsaOptions($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TimestampAuthorityOptions::class);
        $this->tsa_options = $var;

        return $this;
    }

    /**
     * Optional options for integrated timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold: 0
     * Disable: true
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TlogIntegratedTimestampOptions integrated_ts_options = 6;</code>
     * @return \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogIntegratedTimestampOptions|null
     */
    public function getIntegratedTsOptions()
    {
        return $this->integrated_ts_options;
    }

    public function hasIntegratedTsOptions()
    {
        return isset($this->integrated_ts_options);
    }

    public function clearIntegratedTsOptions()
    {
        unset($this->integrated_ts_options);
    }

    /**
     * Optional options for integrated timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold: 0
     * Disable: true
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.TlogIntegratedTimestampOptions integrated_ts_options = 6;</code>
     * @param \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogIntegratedTimestampOptions $var
     * @return $this
     */
    public function setIntegratedTsOptions($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\TlogIntegratedTimestampOptions::class);
        $this->integrated_ts_options = $var;

        return $this;
    }

    /**
     * Optional options for observed timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold 1
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.ObserverTimestampOptions observer_options = 7;</code>
     * @return \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\ObserverTimestampOptions|null
     */
    public function getObserverOptions()
    {
        return $this->observer_options;
    }

    public function hasObserverOptions()
    {
        return isset($this->observer_options);
    }

    public function clearObserverOptions()
    {
        unset($this->observer_options);
    }

    /**
     * Optional options for observed timestamp verification.
     * If none is provided, the default verification options are:
     * Threshold 1
     * Disable: false
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.ArtifactVerificationOptions.ObserverTimestampOptions observer_options = 7;</code>
     * @param \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\ObserverTimestampOptions $var
     * @return $this
     */
    public function setObserverOptions($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions\ObserverTimestampOptions::class);
        $this->observer_options = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getSigners()
    {
        return $this->whichOneof("signers");
    }

}

