<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.verification.v1.Artifact</code>
 */
class Artifact extends \Google\Protobuf\Internal\Message
{
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $artifact_uri
     *           Location of the artifact
     *     @type string $artifact
     *           The raw bytes of the artifact
     *     @type \Dev\Sigstore\Common\V1\HashOutput $artifact_digest
     *           Digest of the artifact. SHOULD NOT be used when verifying an
     *           in-toto attestation as the subject digest cannot be
     *           reconstructed. This option will not work with Ed25519
     *           signatures, use Ed25519Ph or another algorithm instead.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * Location of the artifact
     *
     * Generated from protobuf field <code>string artifact_uri = 1;</code>
     * @return string
     */
    public function getArtifactUri()
    {
        return $this->readOneof(1);
    }

    public function hasArtifactUri()
    {
        return $this->hasOneof(1);
    }

    /**
     * Location of the artifact
     *
     * Generated from protobuf field <code>string artifact_uri = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifactUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The raw bytes of the artifact
     *
     * Generated from protobuf field <code>bytes artifact = 2;</code>
     * @return string
     */
    public function getArtifact()
    {
        return $this->readOneof(2);
    }

    public function hasArtifact()
    {
        return $this->hasOneof(2);
    }

    /**
     * The raw bytes of the artifact
     *
     * Generated from protobuf field <code>bytes artifact = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifact($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Digest of the artifact. SHOULD NOT be used when verifying an
     * in-toto attestation as the subject digest cannot be
     * reconstructed. This option will not work with Ed25519
     * signatures, use Ed25519Ph or another algorithm instead.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashOutput artifact_digest = 3;</code>
     * @return \Dev\Sigstore\Common\V1\HashOutput|null
     */
    public function getArtifactDigest()
    {
        return $this->readOneof(3);
    }

    public function hasArtifactDigest()
    {
        return $this->hasOneof(3);
    }

    /**
     * Digest of the artifact. SHOULD NOT be used when verifying an
     * in-toto attestation as the subject digest cannot be
     * reconstructed. This option will not work with Ed25519
     * signatures, use Ed25519Ph or another algorithm instead.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashOutput artifact_digest = 3;</code>
     * @param \Dev\Sigstore\Common\V1\HashOutput $var
     * @return $this
     */
    public function setArtifactDigest($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\HashOutput::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

