<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The identity of a X.509 Certificate signer.
 *
 * Generated from protobuf message <code>dev.sigstore.verification.v1.CertificateIdentity</code>
 */
class CertificateIdentity extends \Google\Protobuf\Internal\Message
{
    /**
     * The X.509v3 issuer extension (OID 1.3.6.1.4.1.57264.1.1)
     *
     * Generated from protobuf field <code>string issuer = 1;</code>
     */
    protected $issuer = '';
    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.SubjectAlternativeName san = 2;</code>
     */
    protected $san = null;
    /**
     * An unordered list of OIDs that must be verified.
     * All OID/values provided in this list MUST exactly match against
     * the values in the certificate for verification to be successful.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.ObjectIdentifierValuePair oids = 3;</code>
     */
    private $oids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $issuer
     *           The X.509v3 issuer extension (OID 1.3.6.1.4.1.57264.1.1)
     *     @type \Dev\Sigstore\Common\V1\SubjectAlternativeName $san
     *     @type array<\Dev\Sigstore\Common\V1\ObjectIdentifierValuePair>|\Google\Protobuf\Internal\RepeatedField $oids
     *           An unordered list of OIDs that must be verified.
     *           All OID/values provided in this list MUST exactly match against
     *           the values in the certificate for verification to be successful.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * The X.509v3 issuer extension (OID 1.3.6.1.4.1.57264.1.1)
     *
     * Generated from protobuf field <code>string issuer = 1;</code>
     * @return string
     */
    public function getIssuer()
    {
        return $this->issuer;
    }

    /**
     * The X.509v3 issuer extension (OID 1.3.6.1.4.1.57264.1.1)
     *
     * Generated from protobuf field <code>string issuer = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->issuer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.SubjectAlternativeName san = 2;</code>
     * @return \Dev\Sigstore\Common\V1\SubjectAlternativeName|null
     */
    public function getSan()
    {
        return $this->san;
    }

    public function hasSan()
    {
        return isset($this->san);
    }

    public function clearSan()
    {
        unset($this->san);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.SubjectAlternativeName san = 2;</code>
     * @param \Dev\Sigstore\Common\V1\SubjectAlternativeName $var
     * @return $this
     */
    public function setSan($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\SubjectAlternativeName::class);
        $this->san = $var;

        return $this;
    }

    /**
     * An unordered list of OIDs that must be verified.
     * All OID/values provided in this list MUST exactly match against
     * the values in the certificate for verification to be successful.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.ObjectIdentifierValuePair oids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOids()
    {
        return $this->oids;
    }

    /**
     * An unordered list of OIDs that must be verified.
     * All OID/values provided in this list MUST exactly match against
     * the values in the certificate for verification to be successful.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.ObjectIdentifierValuePair oids = 3;</code>
     * @param array<\Dev\Sigstore\Common\V1\ObjectIdentifierValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Common\V1\ObjectIdentifierValuePair::class);
        $this->oids = $arr;

        return $this;
    }

}

