<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.verification.v1.CertificateIdentities</code>
 */
class CertificateIdentities extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.verification.v1.CertificateIdentity identities = 1;</code>
     */
    private $identities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Dev\Sigstore\Verification\V1\CertificateIdentity>|\Google\Protobuf\Internal\RepeatedField $identities
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.verification.v1.CertificateIdentity identities = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIdentities()
    {
        return $this->identities;
    }

    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.verification.v1.CertificateIdentity identities = 1;</code>
     * @param array<\Dev\Sigstore\Verification\V1\CertificateIdentity>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIdentities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Verification\V1\CertificateIdentity::class);
        $this->identities = $arr;

        return $this;
    }

}

