<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Input captures all that is needed to call the bundle verification method,
 * to verify a single artifact referenced by the bundle.
 *
 * Generated from protobuf message <code>dev.sigstore.verification.v1.Input</code>
 */
class Input extends \Google\Protobuf\Internal\Message
{
    /**
     * The verification materials provided during a bundle verification.
     * The running process is usually preloaded with a "global"
     * dev.sisgtore.trustroot.TrustedRoot.v1 instance. Prior to
     * verifying an artifact (i.e a bundle), and/or based on current
     * policy, some selection is expected to happen, to filter out the
     * exact certificate authority to use, which transparency logs are
     * relevant etc. The result should b ecaptured in the
     * `artifact_trust_root`.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.TrustedRoot artifact_trust_root = 1;</code>
     */
    protected $artifact_trust_root = null;
    /**
     * Generated from protobuf field <code>.dev.sigstore.verification.v1.ArtifactVerificationOptions artifact_verification_options = 2;</code>
     */
    protected $artifact_verification_options = null;
    /**
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.Bundle bundle = 3;</code>
     */
    protected $bundle = null;
    /**
     * If the bundle contains a message signature, the artifact must be
     * provided.
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.Artifact artifact = 4;</code>
     */
    protected $artifact = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Dev\Sigstore\Trustroot\V1\TrustedRoot $artifact_trust_root
     *           The verification materials provided during a bundle verification.
     *           The running process is usually preloaded with a "global"
     *           dev.sisgtore.trustroot.TrustedRoot.v1 instance. Prior to
     *           verifying an artifact (i.e a bundle), and/or based on current
     *           policy, some selection is expected to happen, to filter out the
     *           exact certificate authority to use, which transparency logs are
     *           relevant etc. The result should b ecaptured in the
     *           `artifact_trust_root`.
     *     @type \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions $artifact_verification_options
     *     @type \Dev\Sigstore\Bundle\V1\Bundle $bundle
     *     @type \Dev\Sigstore\Verification\V1\Artifact $artifact
     *           If the bundle contains a message signature, the artifact must be
     *           provided.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * The verification materials provided during a bundle verification.
     * The running process is usually preloaded with a "global"
     * dev.sisgtore.trustroot.TrustedRoot.v1 instance. Prior to
     * verifying an artifact (i.e a bundle), and/or based on current
     * policy, some selection is expected to happen, to filter out the
     * exact certificate authority to use, which transparency logs are
     * relevant etc. The result should b ecaptured in the
     * `artifact_trust_root`.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.TrustedRoot artifact_trust_root = 1;</code>
     * @return \Dev\Sigstore\Trustroot\V1\TrustedRoot|null
     */
    public function getArtifactTrustRoot()
    {
        return $this->artifact_trust_root;
    }

    public function hasArtifactTrustRoot()
    {
        return isset($this->artifact_trust_root);
    }

    public function clearArtifactTrustRoot()
    {
        unset($this->artifact_trust_root);
    }

    /**
     * The verification materials provided during a bundle verification.
     * The running process is usually preloaded with a "global"
     * dev.sisgtore.trustroot.TrustedRoot.v1 instance. Prior to
     * verifying an artifact (i.e a bundle), and/or based on current
     * policy, some selection is expected to happen, to filter out the
     * exact certificate authority to use, which transparency logs are
     * relevant etc. The result should b ecaptured in the
     * `artifact_trust_root`.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.TrustedRoot artifact_trust_root = 1;</code>
     * @param \Dev\Sigstore\Trustroot\V1\TrustedRoot $var
     * @return $this
     */
    public function setArtifactTrustRoot($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Trustroot\V1\TrustedRoot::class);
        $this->artifact_trust_root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.verification.v1.ArtifactVerificationOptions artifact_verification_options = 2;</code>
     * @return \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions|null
     */
    public function getArtifactVerificationOptions()
    {
        return $this->artifact_verification_options;
    }

    public function hasArtifactVerificationOptions()
    {
        return isset($this->artifact_verification_options);
    }

    public function clearArtifactVerificationOptions()
    {
        unset($this->artifact_verification_options);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.verification.v1.ArtifactVerificationOptions artifact_verification_options = 2;</code>
     * @param \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions $var
     * @return $this
     */
    public function setArtifactVerificationOptions($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\ArtifactVerificationOptions::class);
        $this->artifact_verification_options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.Bundle bundle = 3;</code>
     * @return \Dev\Sigstore\Bundle\V1\Bundle|null
     */
    public function getBundle()
    {
        return $this->bundle;
    }

    public function hasBundle()
    {
        return isset($this->bundle);
    }

    public function clearBundle()
    {
        unset($this->bundle);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.Bundle bundle = 3;</code>
     * @param \Dev\Sigstore\Bundle\V1\Bundle $var
     * @return $this
     */
    public function setBundle($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Bundle\V1\Bundle::class);
        $this->bundle = $var;

        return $this;
    }

    /**
     * If the bundle contains a message signature, the artifact must be
     * provided.
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.Artifact artifact = 4;</code>
     * @return \Dev\Sigstore\Verification\V1\Artifact|null
     */
    public function getArtifact()
    {
        return $this->artifact;
    }

    public function hasArtifact()
    {
        return isset($this->artifact);
    }

    public function clearArtifact()
    {
        unset($this->artifact);
    }

    /**
     * If the bundle contains a message signature, the artifact must be
     * provided.
     *
     * Generated from protobuf field <code>optional .dev.sigstore.verification.v1.Artifact artifact = 4;</code>
     * @param \Dev\Sigstore\Verification\V1\Artifact $var
     * @return $this
     */
    public function setArtifact($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Verification\V1\Artifact::class);
        $this->artifact = $var;

        return $this;
    }

}

