<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.verification.v1.PublicKeyIdentities</code>
 */
class PublicKeyIdentities extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.PublicKey public_keys = 1;</code>
     */
    private $public_keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Dev\Sigstore\Common\V1\PublicKey>|\Google\Protobuf\Internal\RepeatedField $public_keys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.PublicKey public_keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPublicKeys()
    {
        return $this->public_keys;
    }

    /**
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.PublicKey public_keys = 1;</code>
     * @param array<\Dev\Sigstore\Common\V1\PublicKey>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPublicKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Common\V1\PublicKey::class);
        $this->public_keys = $arr;

        return $this;
    }

}

