<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_rekor.proto

namespace Dev\Sigstore\Rekor\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The checkpoint MUST contain an origin string as a unique log identifier,
 * the tree size, and the root hash. It MAY also be followed by optional data,
 * and clients MUST NOT assume optional data. The checkpoint MUST also contain
 * a signature over the root hash (tree head). The checkpoint MAY contain additional
 * signatures, but the first SHOULD be the signature from the log. Checkpoint contents
 * are concatenated with newlines into a single string.
 * The checkpoint format is described in
 * https://github.com/transparency-dev/formats/blob/main/log/README.md
 * and https://github.com/C2SP/C2SP/blob/main/tlog-checkpoint.md.
 * An example implementation can be found in https://github.com/sigstore/rekor/blob/main/pkg/util/signed_note.go
 *
 * Generated from protobuf message <code>dev.sigstore.rekor.v1.Checkpoint</code>
 */
class Checkpoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string envelope = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $envelope = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $envelope
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreRekor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string envelope = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getEnvelope()
    {
        return $this->envelope;
    }

    /**
     * Generated from protobuf field <code>string envelope = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setEnvelope($var)
    {
        GPBUtil::checkString($var, True);
        $this->envelope = $var;

        return $this;
    }

}

