<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_rekor.proto

namespace Dev\Sigstore\Rekor\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The inclusion promise is calculated by Rekor. It's calculated as a
 * signature over a canonical JSON serialization of the persisted entry, the
 * log ID, log index and the integration timestamp.
 * See https://github.com/sigstore/rekor/blob/a6e58f72b6b18cc06cefe61808efd562b9726330/pkg/api/entries.go#L54
 * The format of the signature depends on the transparency log's public key.
 * If the signature algorithm requires a hash function and/or a signature
 * scheme (e.g. RSA) those has to be retrieved out-of-band from the log's
 * operators, together with the public key.
 * This is used to verify the integration timestamp's value and that the log
 * has promised to include the entry.
 *
 * Generated from protobuf message <code>dev.sigstore.rekor.v1.InclusionPromise</code>
 */
class InclusionPromise extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes signed_entry_timestamp = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $signed_entry_timestamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signed_entry_timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreRekor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes signed_entry_timestamp = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getSignedEntryTimestamp()
    {
        return $this->signed_entry_timestamp;
    }

    /**
     * Generated from protobuf field <code>bytes signed_entry_timestamp = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setSignedEntryTimestamp($var)
    {
        GPBUtil::checkString($var, False);
        $this->signed_entry_timestamp = $var;

        return $this;
    }

}

