<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_rekor.proto

namespace Dev\Sigstore\Rekor\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * InclusionProof is the proof returned from the transparency log. Can
 * be used for offline or online verification against the log.
 *
 * Generated from protobuf message <code>dev.sigstore.rekor.v1.InclusionProof</code>
 */
class InclusionProof extends \Google\Protobuf\Internal\Message
{
    /**
     * The index of the entry in the tree it was written to.
     *
     * Generated from protobuf field <code>int64 log_index = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $log_index = 0;
    /**
     * The hash digest stored at the root of the merkle tree at the time
     * the proof was generated.
     *
     * Generated from protobuf field <code>bytes root_hash = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $root_hash = '';
    /**
     * The size of the merkle tree at the time the proof was generated.
     *
     * Generated from protobuf field <code>int64 tree_size = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $tree_size = 0;
    /**
     * A list of hashes required to compute the inclusion proof, sorted
     * in order from leaf to root.
     * Note that leaf and root hashes are not included.
     * The root hash is available separately in this message, and the
     * leaf hash should be calculated by the client.
     *
     * Generated from protobuf field <code>repeated bytes hashes = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private $hashes;
    /**
     * Signature of the tree head, as of the time of this proof was
     * generated. See above info on 'Checkpoint' for more details.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.Checkpoint checkpoint = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $checkpoint = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $log_index
     *           The index of the entry in the tree it was written to.
     *     @type string $root_hash
     *           The hash digest stored at the root of the merkle tree at the time
     *           the proof was generated.
     *     @type int|string $tree_size
     *           The size of the merkle tree at the time the proof was generated.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $hashes
     *           A list of hashes required to compute the inclusion proof, sorted
     *           in order from leaf to root.
     *           Note that leaf and root hashes are not included.
     *           The root hash is available separately in this message, and the
     *           leaf hash should be calculated by the client.
     *     @type \Dev\Sigstore\Rekor\V1\Checkpoint $checkpoint
     *           Signature of the tree head, as of the time of this proof was
     *           generated. See above info on 'Checkpoint' for more details.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreRekor::initOnce();
        parent::__construct($data);
    }

    /**
     * The index of the entry in the tree it was written to.
     *
     * Generated from protobuf field <code>int64 log_index = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int|string
     */
    public function getLogIndex()
    {
        return $this->log_index;
    }

    /**
     * The index of the entry in the tree it was written to.
     *
     * Generated from protobuf field <code>int64 log_index = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int|string $var
     * @return $this
     */
    public function setLogIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->log_index = $var;

        return $this;
    }

    /**
     * The hash digest stored at the root of the merkle tree at the time
     * the proof was generated.
     *
     * Generated from protobuf field <code>bytes root_hash = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getRootHash()
    {
        return $this->root_hash;
    }

    /**
     * The hash digest stored at the root of the merkle tree at the time
     * the proof was generated.
     *
     * Generated from protobuf field <code>bytes root_hash = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setRootHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->root_hash = $var;

        return $this;
    }

    /**
     * The size of the merkle tree at the time the proof was generated.
     *
     * Generated from protobuf field <code>int64 tree_size = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int|string
     */
    public function getTreeSize()
    {
        return $this->tree_size;
    }

    /**
     * The size of the merkle tree at the time the proof was generated.
     *
     * Generated from protobuf field <code>int64 tree_size = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTreeSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->tree_size = $var;

        return $this;
    }

    /**
     * A list of hashes required to compute the inclusion proof, sorted
     * in order from leaf to root.
     * Note that leaf and root hashes are not included.
     * The root hash is available separately in this message, and the
     * leaf hash should be calculated by the client.
     *
     * Generated from protobuf field <code>repeated bytes hashes = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHashes()
    {
        return $this->hashes;
    }

    /**
     * A list of hashes required to compute the inclusion proof, sorted
     * in order from leaf to root.
     * Note that leaf and root hashes are not included.
     * The root hash is available separately in this message, and the
     * leaf hash should be calculated by the client.
     *
     * Generated from protobuf field <code>repeated bytes hashes = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->hashes = $arr;

        return $this;
    }

    /**
     * Signature of the tree head, as of the time of this proof was
     * generated. See above info on 'Checkpoint' for more details.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.Checkpoint checkpoint = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Rekor\V1\Checkpoint|null
     */
    public function getCheckpoint()
    {
        return $this->checkpoint;
    }

    public function hasCheckpoint()
    {
        return isset($this->checkpoint);
    }

    public function clearCheckpoint()
    {
        unset($this->checkpoint);
    }

    /**
     * Signature of the tree head, as of the time of this proof was
     * generated. See above info on 'Checkpoint' for more details.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.Checkpoint checkpoint = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Rekor\V1\Checkpoint $var
     * @return $this
     */
    public function setCheckpoint($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Rekor\V1\Checkpoint::class);
        $this->checkpoint = $var;

        return $this;
    }

}

