<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_rekor.proto

namespace Dev\Sigstore\Rekor\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * KindVersion contains the entry's kind and api version.
 *
 * Generated from protobuf message <code>dev.sigstore.rekor.v1.KindVersion</code>
 */
class KindVersion extends \Google\Protobuf\Internal\Message
{
    /**
     * Kind is the type of entry being stored in the log.
     * See here for a list: https://github.com/sigstore/rekor/tree/main/pkg/types
     *
     * Generated from protobuf field <code>string kind = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $kind = '';
    /**
     * The specific api version of the type.
     *
     * Generated from protobuf field <code>string version = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $kind
     *           Kind is the type of entry being stored in the log.
     *           See here for a list: https://github.com/sigstore/rekor/tree/main/pkg/types
     *     @type string $version
     *           The specific api version of the type.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreRekor::initOnce();
        parent::__construct($data);
    }

    /**
     * Kind is the type of entry being stored in the log.
     * See here for a list: https://github.com/sigstore/rekor/tree/main/pkg/types
     *
     * Generated from protobuf field <code>string kind = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Kind is the type of entry being stored in the log.
     * See here for a list: https://github.com/sigstore/rekor/tree/main/pkg/types
     *
     * Generated from protobuf field <code>string kind = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkString($var, True);
        $this->kind = $var;

        return $this;
    }

    /**
     * The specific api version of the type.
     *
     * Generated from protobuf field <code>string version = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * The specific api version of the type.
     *
     * Generated from protobuf field <code>string version = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

