<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_rekor.proto

namespace Dev\Sigstore\Rekor\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TransparencyLogEntry captures all the details required from Rekor to
 * reconstruct an entry, given that the payload is provided via other means.
 * This type can easily be created from the existing response from Rekor.
 * Future iterations could rely on Rekor returning the minimal set of
 * attributes (excluding the payload) that are required for verifying the
 * inclusion promise. The inclusion promise (called SignedEntryTimestamp in
 * the response from Rekor) is similar to a Signed Certificate Timestamp
 * as described here https://www.rfc-editor.org/rfc/rfc6962.html#section-3.2.
 *
 * Generated from protobuf message <code>dev.sigstore.rekor.v1.TransparencyLogEntry</code>
 */
class TransparencyLogEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * The global index of the entry, used when querying the log by index.
     *
     * Generated from protobuf field <code>int64 log_index = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $log_index = 0;
    /**
     * The unique identifier of the log.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId log_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $log_id = null;
    /**
     * The kind (type) and version of the object associated with this
     * entry. These values are required to construct the entry during
     * verification.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.KindVersion kind_version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $kind_version = null;
    /**
     * The UNIX timestamp from the log when the entry was persisted.
     * The integration time MUST NOT be trusted if inclusion_promise
     * is omitted.
     *
     * Generated from protobuf field <code>int64 integrated_time = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $integrated_time = 0;
    /**
     * The inclusion promise/signed entry timestamp from the log.
     * Required for v0.1 bundles, and MUST be verified.
     * Optional for >= v0.2 bundles if another suitable source of
     * time is present (such as another source of signed time,
     * or the current system time for long-lived certificates).
     * MUST be verified if no other suitable source of time is present,
     * and SHOULD be verified otherwise.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.InclusionPromise inclusion_promise = 5;</code>
     */
    protected $inclusion_promise = null;
    /**
     * The inclusion proof can be used for offline or online verification
     * that the entry was appended to the log, and that the log has not been
     * altered.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.InclusionProof inclusion_proof = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $inclusion_proof = null;
    /**
     * Optional. The canonicalized transparency log entry, used to
     * reconstruct the Signed Entry Timestamp (SET) during verification.
     * The contents of this field are the same as the `body` field in
     * a Rekor response, meaning that it does **not** include the "full"
     * canonicalized form (of log index, ID, etc.) which are
     * exposed as separate fields. The verifier is responsible for
     * combining the `canonicalized_body`, `log_index`, `log_id`,
     * and `integrated_time` into the payload that the SET's signature
     * is generated over.
     * This field is intended to be used in cases where the SET cannot be
     * produced determinisitically (e.g. inconsistent JSON field ordering,
     * differing whitespace, etc).
     * If set, clients MUST verify that the signature referenced in the
     * `canonicalized_body` matches the signature provided in the
     * `Bundle.content`.
     * If not set, clients are responsible for constructing an equivalent
     * payload from other sources to verify the signature.
     *
     * Generated from protobuf field <code>bytes canonicalized_body = 7;</code>
     */
    protected $canonicalized_body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $log_index
     *           The global index of the entry, used when querying the log by index.
     *     @type \Dev\Sigstore\Common\V1\LogId $log_id
     *           The unique identifier of the log.
     *     @type \Dev\Sigstore\Rekor\V1\KindVersion $kind_version
     *           The kind (type) and version of the object associated with this
     *           entry. These values are required to construct the entry during
     *           verification.
     *     @type int|string $integrated_time
     *           The UNIX timestamp from the log when the entry was persisted.
     *           The integration time MUST NOT be trusted if inclusion_promise
     *           is omitted.
     *     @type \Dev\Sigstore\Rekor\V1\InclusionPromise $inclusion_promise
     *           The inclusion promise/signed entry timestamp from the log.
     *           Required for v0.1 bundles, and MUST be verified.
     *           Optional for >= v0.2 bundles if another suitable source of
     *           time is present (such as another source of signed time,
     *           or the current system time for long-lived certificates).
     *           MUST be verified if no other suitable source of time is present,
     *           and SHOULD be verified otherwise.
     *     @type \Dev\Sigstore\Rekor\V1\InclusionProof $inclusion_proof
     *           The inclusion proof can be used for offline or online verification
     *           that the entry was appended to the log, and that the log has not been
     *           altered.
     *     @type string $canonicalized_body
     *           Optional. The canonicalized transparency log entry, used to
     *           reconstruct the Signed Entry Timestamp (SET) during verification.
     *           The contents of this field are the same as the `body` field in
     *           a Rekor response, meaning that it does **not** include the "full"
     *           canonicalized form (of log index, ID, etc.) which are
     *           exposed as separate fields. The verifier is responsible for
     *           combining the `canonicalized_body`, `log_index`, `log_id`,
     *           and `integrated_time` into the payload that the SET's signature
     *           is generated over.
     *           This field is intended to be used in cases where the SET cannot be
     *           produced determinisitically (e.g. inconsistent JSON field ordering,
     *           differing whitespace, etc).
     *           If set, clients MUST verify that the signature referenced in the
     *           `canonicalized_body` matches the signature provided in the
     *           `Bundle.content`.
     *           If not set, clients are responsible for constructing an equivalent
     *           payload from other sources to verify the signature.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreRekor::initOnce();
        parent::__construct($data);
    }

    /**
     * The global index of the entry, used when querying the log by index.
     *
     * Generated from protobuf field <code>int64 log_index = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int|string
     */
    public function getLogIndex()
    {
        return $this->log_index;
    }

    /**
     * The global index of the entry, used when querying the log by index.
     *
     * Generated from protobuf field <code>int64 log_index = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int|string $var
     * @return $this
     */
    public function setLogIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->log_index = $var;

        return $this;
    }

    /**
     * The unique identifier of the log.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId log_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Common\V1\LogId|null
     */
    public function getLogId()
    {
        return $this->log_id;
    }

    public function hasLogId()
    {
        return isset($this->log_id);
    }

    public function clearLogId()
    {
        unset($this->log_id);
    }

    /**
     * The unique identifier of the log.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId log_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Common\V1\LogId $var
     * @return $this
     */
    public function setLogId($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\LogId::class);
        $this->log_id = $var;

        return $this;
    }

    /**
     * The kind (type) and version of the object associated with this
     * entry. These values are required to construct the entry during
     * verification.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.KindVersion kind_version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Rekor\V1\KindVersion|null
     */
    public function getKindVersion()
    {
        return $this->kind_version;
    }

    public function hasKindVersion()
    {
        return isset($this->kind_version);
    }

    public function clearKindVersion()
    {
        unset($this->kind_version);
    }

    /**
     * The kind (type) and version of the object associated with this
     * entry. These values are required to construct the entry during
     * verification.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.KindVersion kind_version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Rekor\V1\KindVersion $var
     * @return $this
     */
    public function setKindVersion($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Rekor\V1\KindVersion::class);
        $this->kind_version = $var;

        return $this;
    }

    /**
     * The UNIX timestamp from the log when the entry was persisted.
     * The integration time MUST NOT be trusted if inclusion_promise
     * is omitted.
     *
     * Generated from protobuf field <code>int64 integrated_time = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int|string
     */
    public function getIntegratedTime()
    {
        return $this->integrated_time;
    }

    /**
     * The UNIX timestamp from the log when the entry was persisted.
     * The integration time MUST NOT be trusted if inclusion_promise
     * is omitted.
     *
     * Generated from protobuf field <code>int64 integrated_time = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntegratedTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->integrated_time = $var;

        return $this;
    }

    /**
     * The inclusion promise/signed entry timestamp from the log.
     * Required for v0.1 bundles, and MUST be verified.
     * Optional for >= v0.2 bundles if another suitable source of
     * time is present (such as another source of signed time,
     * or the current system time for long-lived certificates).
     * MUST be verified if no other suitable source of time is present,
     * and SHOULD be verified otherwise.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.InclusionPromise inclusion_promise = 5;</code>
     * @return \Dev\Sigstore\Rekor\V1\InclusionPromise|null
     */
    public function getInclusionPromise()
    {
        return $this->inclusion_promise;
    }

    public function hasInclusionPromise()
    {
        return isset($this->inclusion_promise);
    }

    public function clearInclusionPromise()
    {
        unset($this->inclusion_promise);
    }

    /**
     * The inclusion promise/signed entry timestamp from the log.
     * Required for v0.1 bundles, and MUST be verified.
     * Optional for >= v0.2 bundles if another suitable source of
     * time is present (such as another source of signed time,
     * or the current system time for long-lived certificates).
     * MUST be verified if no other suitable source of time is present,
     * and SHOULD be verified otherwise.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.InclusionPromise inclusion_promise = 5;</code>
     * @param \Dev\Sigstore\Rekor\V1\InclusionPromise $var
     * @return $this
     */
    public function setInclusionPromise($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Rekor\V1\InclusionPromise::class);
        $this->inclusion_promise = $var;

        return $this;
    }

    /**
     * The inclusion proof can be used for offline or online verification
     * that the entry was appended to the log, and that the log has not been
     * altered.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.InclusionProof inclusion_proof = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Rekor\V1\InclusionProof|null
     */
    public function getInclusionProof()
    {
        return $this->inclusion_proof;
    }

    public function hasInclusionProof()
    {
        return isset($this->inclusion_proof);
    }

    public function clearInclusionProof()
    {
        unset($this->inclusion_proof);
    }

    /**
     * The inclusion proof can be used for offline or online verification
     * that the entry was appended to the log, and that the log has not been
     * altered.
     *
     * Generated from protobuf field <code>.dev.sigstore.rekor.v1.InclusionProof inclusion_proof = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Rekor\V1\InclusionProof $var
     * @return $this
     */
    public function setInclusionProof($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Rekor\V1\InclusionProof::class);
        $this->inclusion_proof = $var;

        return $this;
    }

    /**
     * Optional. The canonicalized transparency log entry, used to
     * reconstruct the Signed Entry Timestamp (SET) during verification.
     * The contents of this field are the same as the `body` field in
     * a Rekor response, meaning that it does **not** include the "full"
     * canonicalized form (of log index, ID, etc.) which are
     * exposed as separate fields. The verifier is responsible for
     * combining the `canonicalized_body`, `log_index`, `log_id`,
     * and `integrated_time` into the payload that the SET's signature
     * is generated over.
     * This field is intended to be used in cases where the SET cannot be
     * produced determinisitically (e.g. inconsistent JSON field ordering,
     * differing whitespace, etc).
     * If set, clients MUST verify that the signature referenced in the
     * `canonicalized_body` matches the signature provided in the
     * `Bundle.content`.
     * If not set, clients are responsible for constructing an equivalent
     * payload from other sources to verify the signature.
     *
     * Generated from protobuf field <code>bytes canonicalized_body = 7;</code>
     * @return string
     */
    public function getCanonicalizedBody()
    {
        return $this->canonicalized_body;
    }

    /**
     * Optional. The canonicalized transparency log entry, used to
     * reconstruct the Signed Entry Timestamp (SET) during verification.
     * The contents of this field are the same as the `body` field in
     * a Rekor response, meaning that it does **not** include the "full"
     * canonicalized form (of log index, ID, etc.) which are
     * exposed as separate fields. The verifier is responsible for
     * combining the `canonicalized_body`, `log_index`, `log_id`,
     * and `integrated_time` into the payload that the SET's signature
     * is generated over.
     * This field is intended to be used in cases where the SET cannot be
     * produced determinisitically (e.g. inconsistent JSON field ordering,
     * differing whitespace, etc).
     * If set, clients MUST verify that the signature referenced in the
     * `canonicalized_body` matches the signature provided in the
     * `Bundle.content`.
     * If not set, clients are responsible for constructing an equivalent
     * payload from other sources to verify the signature.
     *
     * Generated from protobuf field <code>bytes canonicalized_body = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCanonicalizedBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->canonicalized_body = $var;

        return $this;
    }

}

