<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CertificateAuthority enlists the information required to identify which
 * CA to use and perform signature verification.
 *
 * Generated from protobuf message <code>dev.sigstore.trustroot.v1.CertificateAuthority</code>
 */
class CertificateAuthority extends \Google\Protobuf\Internal\Message
{
    /**
     * The root certificate MUST be self-signed, and so the subject and
     * issuer are the same.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.DistinguishedName subject = 1;</code>
     */
    protected $subject = null;
    /**
     * The URI identifies the certificate authority.
     * It is RECOMMENDED that the URI is the base URL for the certificate
     * authority, that can be provided to any SDK/client provided
     * by the certificate authority to interact with the certificate
     * authority.
     *
     * Generated from protobuf field <code>string uri = 2;</code>
     */
    protected $uri = '';
    /**
     * The certificate chain for this CA. The last certificate in the chain
     * MUST be the trust anchor. The trust anchor MAY be a self-signed root
     * CA certificate or MAY be an intermediate CA certificate.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.X509CertificateChain cert_chain = 3;</code>
     */
    protected $cert_chain = null;
    /**
     * The time the *entire* chain was valid. This is at max the
     * longest interval when *all* certificates in the chain were valid,
     * but it MAY be shorter. Clients MUST check timestamps against *both*
     * the `valid_for` time range *and* the entire certificate chain.
     * The TimeRange should be considered valid *inclusive* of the
     * endpoints.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.TimeRange valid_for = 4;</code>
     */
    protected $valid_for = null;
    /**
     * The name of the operator of this certificate or timestamp authority.
     * Operator MUST be formatted as a scheme-less URI, e.g. sigstore.dev
     * This MUST be used when there are multiple timestamp authorities to
     * determine if the signed timestamp verification meets a specified
     * threshold, e.g. two signed timestamps from timestamp authorities
     * operated by the same operator should count as only one valid
     * timestamp.
     *
     * Generated from protobuf field <code>string operator = 5;</code>
     */
    protected $operator = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Dev\Sigstore\Common\V1\DistinguishedName $subject
     *           The root certificate MUST be self-signed, and so the subject and
     *           issuer are the same.
     *     @type string $uri
     *           The URI identifies the certificate authority.
     *           It is RECOMMENDED that the URI is the base URL for the certificate
     *           authority, that can be provided to any SDK/client provided
     *           by the certificate authority to interact with the certificate
     *           authority.
     *     @type \Dev\Sigstore\Common\V1\X509CertificateChain $cert_chain
     *           The certificate chain for this CA. The last certificate in the chain
     *           MUST be the trust anchor. The trust anchor MAY be a self-signed root
     *           CA certificate or MAY be an intermediate CA certificate.
     *     @type \Dev\Sigstore\Common\V1\TimeRange $valid_for
     *           The time the *entire* chain was valid. This is at max the
     *           longest interval when *all* certificates in the chain were valid,
     *           but it MAY be shorter. Clients MUST check timestamps against *both*
     *           the `valid_for` time range *and* the entire certificate chain.
     *           The TimeRange should be considered valid *inclusive* of the
     *           endpoints.
     *     @type string $operator
     *           The name of the operator of this certificate or timestamp authority.
     *           Operator MUST be formatted as a scheme-less URI, e.g. sigstore.dev
     *           This MUST be used when there are multiple timestamp authorities to
     *           determine if the signed timestamp verification meets a specified
     *           threshold, e.g. two signed timestamps from timestamp authorities
     *           operated by the same operator should count as only one valid
     *           timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreTrustroot::initOnce();
        parent::__construct($data);
    }

    /**
     * The root certificate MUST be self-signed, and so the subject and
     * issuer are the same.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.DistinguishedName subject = 1;</code>
     * @return \Dev\Sigstore\Common\V1\DistinguishedName|null
     */
    public function getSubject()
    {
        return $this->subject;
    }

    public function hasSubject()
    {
        return isset($this->subject);
    }

    public function clearSubject()
    {
        unset($this->subject);
    }

    /**
     * The root certificate MUST be self-signed, and so the subject and
     * issuer are the same.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.DistinguishedName subject = 1;</code>
     * @param \Dev\Sigstore\Common\V1\DistinguishedName $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\DistinguishedName::class);
        $this->subject = $var;

        return $this;
    }

    /**
     * The URI identifies the certificate authority.
     * It is RECOMMENDED that the URI is the base URL for the certificate
     * authority, that can be provided to any SDK/client provided
     * by the certificate authority to interact with the certificate
     * authority.
     *
     * Generated from protobuf field <code>string uri = 2;</code>
     * @return string
     */
    public function getUri()
    {
        return $this->uri;
    }

    /**
     * The URI identifies the certificate authority.
     * It is RECOMMENDED that the URI is the base URL for the certificate
     * authority, that can be provided to any SDK/client provided
     * by the certificate authority to interact with the certificate
     * authority.
     *
     * Generated from protobuf field <code>string uri = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->uri = $var;

        return $this;
    }

    /**
     * The certificate chain for this CA. The last certificate in the chain
     * MUST be the trust anchor. The trust anchor MAY be a self-signed root
     * CA certificate or MAY be an intermediate CA certificate.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.X509CertificateChain cert_chain = 3;</code>
     * @return \Dev\Sigstore\Common\V1\X509CertificateChain|null
     */
    public function getCertChain()
    {
        return $this->cert_chain;
    }

    public function hasCertChain()
    {
        return isset($this->cert_chain);
    }

    public function clearCertChain()
    {
        unset($this->cert_chain);
    }

    /**
     * The certificate chain for this CA. The last certificate in the chain
     * MUST be the trust anchor. The trust anchor MAY be a self-signed root
     * CA certificate or MAY be an intermediate CA certificate.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.X509CertificateChain cert_chain = 3;</code>
     * @param \Dev\Sigstore\Common\V1\X509CertificateChain $var
     * @return $this
     */
    public function setCertChain($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\X509CertificateChain::class);
        $this->cert_chain = $var;

        return $this;
    }

    /**
     * The time the *entire* chain was valid. This is at max the
     * longest interval when *all* certificates in the chain were valid,
     * but it MAY be shorter. Clients MUST check timestamps against *both*
     * the `valid_for` time range *and* the entire certificate chain.
     * The TimeRange should be considered valid *inclusive* of the
     * endpoints.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.TimeRange valid_for = 4;</code>
     * @return \Dev\Sigstore\Common\V1\TimeRange|null
     */
    public function getValidFor()
    {
        return $this->valid_for;
    }

    public function hasValidFor()
    {
        return isset($this->valid_for);
    }

    public function clearValidFor()
    {
        unset($this->valid_for);
    }

    /**
     * The time the *entire* chain was valid. This is at max the
     * longest interval when *all* certificates in the chain were valid,
     * but it MAY be shorter. Clients MUST check timestamps against *both*
     * the `valid_for` time range *and* the entire certificate chain.
     * The TimeRange should be considered valid *inclusive* of the
     * endpoints.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.TimeRange valid_for = 4;</code>
     * @param \Dev\Sigstore\Common\V1\TimeRange $var
     * @return $this
     */
    public function setValidFor($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\TimeRange::class);
        $this->valid_for = $var;

        return $this;
    }

    /**
     * The name of the operator of this certificate or timestamp authority.
     * Operator MUST be formatted as a scheme-less URI, e.g. sigstore.dev
     * This MUST be used when there are multiple timestamp authorities to
     * determine if the signed timestamp verification meets a specified
     * threshold, e.g. two signed timestamps from timestamp authorities
     * operated by the same operator should count as only one valid
     * timestamp.
     *
     * Generated from protobuf field <code>string operator = 5;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * The name of the operator of this certificate or timestamp authority.
     * Operator MUST be formatted as a scheme-less URI, e.g. sigstore.dev
     * This MUST be used when there are multiple timestamp authorities to
     * determine if the signed timestamp verification meets a specified
     * threshold, e.g. two signed timestamps from timestamp authorities
     * operated by the same operator should count as only one valid
     * timestamp.
     *
     * Generated from protobuf field <code>string operator = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

}

