<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ClientTrustConfig describes the complete state needed by a client
 * to perform both signing and verification operations against a particular
 * instance of Sigstore.
 *
 * Generated from protobuf message <code>dev.sigstore.trustroot.v1.ClientTrustConfig</code>
 */
class ClientTrustConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * MUST be application/vnd.dev.sigstore.clienttrustconfig.v0.1+json
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     */
    protected $media_type = '';
    /**
     * The root of trust, which MUST be present.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.TrustedRoot trusted_root = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $trusted_root = null;
    /**
     * Configuration for signing clients, which MUST be present.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.SigningConfig signing_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $signing_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $media_type
     *           MUST be application/vnd.dev.sigstore.clienttrustconfig.v0.1+json
     *     @type \Dev\Sigstore\Trustroot\V1\TrustedRoot $trusted_root
     *           The root of trust, which MUST be present.
     *     @type \Dev\Sigstore\Trustroot\V1\SigningConfig $signing_config
     *           Configuration for signing clients, which MUST be present.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreTrustroot::initOnce();
        parent::__construct($data);
    }

    /**
     * MUST be application/vnd.dev.sigstore.clienttrustconfig.v0.1+json
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     * @return string
     */
    public function getMediaType()
    {
        return $this->media_type;
    }

    /**
     * MUST be application/vnd.dev.sigstore.clienttrustconfig.v0.1+json
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->media_type = $var;

        return $this;
    }

    /**
     * The root of trust, which MUST be present.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.TrustedRoot trusted_root = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Trustroot\V1\TrustedRoot|null
     */
    public function getTrustedRoot()
    {
        return $this->trusted_root;
    }

    public function hasTrustedRoot()
    {
        return isset($this->trusted_root);
    }

    public function clearTrustedRoot()
    {
        unset($this->trusted_root);
    }

    /**
     * The root of trust, which MUST be present.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.TrustedRoot trusted_root = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Trustroot\V1\TrustedRoot $var
     * @return $this
     */
    public function setTrustedRoot($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Trustroot\V1\TrustedRoot::class);
        $this->trusted_root = $var;

        return $this;
    }

    /**
     * Configuration for signing clients, which MUST be present.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.SigningConfig signing_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Trustroot\V1\SigningConfig|null
     */
    public function getSigningConfig()
    {
        return $this->signing_config;
    }

    public function hasSigningConfig()
    {
        return isset($this->signing_config);
    }

    public function clearSigningConfig()
    {
        unset($this->signing_config);
    }

    /**
     * Configuration for signing clients, which MUST be present.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.SigningConfig signing_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Trustroot\V1\SigningConfig $var
     * @return $this
     */
    public function setSigningConfig($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Trustroot\V1\SigningConfig::class);
        $this->signing_config = $var;

        return $this;
    }

}

