<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ServiceConfiguration specifies how a client should select a set of
 * Services to connect to, along with a count when a specific number
 * of Services is requested.
 *
 * Generated from protobuf message <code>dev.sigstore.trustroot.v1.ServiceConfiguration</code>
 */
class ServiceConfiguration extends \Google\Protobuf\Internal\Message
{
    /**
     * How a client should select a set of Services to connect to.
     * Clients SHOULD NOT select services from multiple API versions.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceSelector selector = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $selector = 0;
    /**
     * count specifies the number of Services the client should use.
     * Only used when selector is set to EXACT, and count MUST be greater
     * than 0. count MUST be less than or equal to the number of Services.
     * Clients MUST return an error is there are not enough services
     * that meet selection criteria.
     *
     * Generated from protobuf field <code>uint32 count = 2;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $selector
     *           How a client should select a set of Services to connect to.
     *           Clients SHOULD NOT select services from multiple API versions.
     *     @type int $count
     *           count specifies the number of Services the client should use.
     *           Only used when selector is set to EXACT, and count MUST be greater
     *           than 0. count MUST be less than or equal to the number of Services.
     *           Clients MUST return an error is there are not enough services
     *           that meet selection criteria.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreTrustroot::initOnce();
        parent::__construct($data);
    }

    /**
     * How a client should select a set of Services to connect to.
     * Clients SHOULD NOT select services from multiple API versions.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceSelector selector = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int
     */
    public function getSelector()
    {
        return $this->selector;
    }

    /**
     * How a client should select a set of Services to connect to.
     * Clients SHOULD NOT select services from multiple API versions.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceSelector selector = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int $var
     * @return $this
     */
    public function setSelector($var)
    {
        GPBUtil::checkEnum($var, \Dev\Sigstore\Trustroot\V1\ServiceSelector::class);
        $this->selector = $var;

        return $this;
    }

    /**
     * count specifies the number of Services the client should use.
     * Only used when selector is set to EXACT, and count MUST be greater
     * than 0. count MUST be less than or equal to the number of Services.
     * Clients MUST return an error is there are not enough services
     * that meet selection criteria.
     *
     * Generated from protobuf field <code>uint32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * count specifies the number of Services the client should use.
     * Only used when selector is set to EXACT, and count MUST be greater
     * than 0. count MUST be less than or equal to the number of Services.
     * Clients MUST return an error is there are not enough services
     * that meet selection criteria.
     *
     * Generated from protobuf field <code>uint32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

}

