<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Service represents an instance of a service that is a part of Sigstore infrastructure.
 * When selecting one or multiple services from a list of services, clients MUST:
 * * Use the API version hint to determine the service with the highest API version
 *   that the client is compatible with.
 * * Only select services within the specified validity period and that have the
 *   newest validity start date.
 * When selecting multiple services, clients MUST:
 * * Use the ServiceConfiguration to determine how many services MUST be selected.
 *   Clients MUST return an error if there are not enough services that meet the
 *   selection criteria.
 * * Group services by `operator` and select at most one service from an operator.
 *   During verification, clients MUST treat valid verification metadata from the
 *   operator as valid only once towards a threshold.
 * * Select services from only the highest supported API version.
 *
 * Generated from protobuf message <code>dev.sigstore.trustroot.v1.Service</code>
 */
class Service extends \Google\Protobuf\Internal\Message
{
    /**
     * URL of the service. MUST include scheme and authority. MAY include path.
     *
     * Generated from protobuf field <code>string url = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $url = '';
    /**
     * Specifies the major API version. A value of 0 represents a service that
     * has not yet been released.
     *
     * Generated from protobuf field <code>uint32 major_api_version = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $major_api_version = 0;
    /**
     * Validity period of a service. A service that has only a start date
     * SHOULD be considered the most recent instance of that service, but
     * the client MUST NOT assume there is only one valid instance.
     * The TimeRange MUST be considered valid *inclusive* of the
     * endpoints.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.TimeRange valid_for = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $valid_for = null;
    /**
     * Specifies the name of the service operator. When selecting multiple
     * services, clients MUST use the operator to select services from
     * distinct operators. Operator MUST be formatted as a scheme-less
     * URI, e.g. sigstore.dev
     *
     * Generated from protobuf field <code>string operator = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $operator = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *           URL of the service. MUST include scheme and authority. MAY include path.
     *     @type int $major_api_version
     *           Specifies the major API version. A value of 0 represents a service that
     *           has not yet been released.
     *     @type \Dev\Sigstore\Common\V1\TimeRange $valid_for
     *           Validity period of a service. A service that has only a start date
     *           SHOULD be considered the most recent instance of that service, but
     *           the client MUST NOT assume there is only one valid instance.
     *           The TimeRange MUST be considered valid *inclusive* of the
     *           endpoints.
     *     @type string $operator
     *           Specifies the name of the service operator. When selecting multiple
     *           services, clients MUST use the operator to select services from
     *           distinct operators. Operator MUST be formatted as a scheme-less
     *           URI, e.g. sigstore.dev
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreTrustroot::initOnce();
        parent::__construct($data);
    }

    /**
     * URL of the service. MUST include scheme and authority. MAY include path.
     *
     * Generated from protobuf field <code>string url = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * URL of the service. MUST include scheme and authority. MAY include path.
     *
     * Generated from protobuf field <code>string url = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Specifies the major API version. A value of 0 represents a service that
     * has not yet been released.
     *
     * Generated from protobuf field <code>uint32 major_api_version = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int
     */
    public function getMajorApiVersion()
    {
        return $this->major_api_version;
    }

    /**
     * Specifies the major API version. A value of 0 represents a service that
     * has not yet been released.
     *
     * Generated from protobuf field <code>uint32 major_api_version = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int $var
     * @return $this
     */
    public function setMajorApiVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->major_api_version = $var;

        return $this;
    }

    /**
     * Validity period of a service. A service that has only a start date
     * SHOULD be considered the most recent instance of that service, but
     * the client MUST NOT assume there is only one valid instance.
     * The TimeRange MUST be considered valid *inclusive* of the
     * endpoints.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.TimeRange valid_for = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Common\V1\TimeRange|null
     */
    public function getValidFor()
    {
        return $this->valid_for;
    }

    public function hasValidFor()
    {
        return isset($this->valid_for);
    }

    public function clearValidFor()
    {
        unset($this->valid_for);
    }

    /**
     * Validity period of a service. A service that has only a start date
     * SHOULD be considered the most recent instance of that service, but
     * the client MUST NOT assume there is only one valid instance.
     * The TimeRange MUST be considered valid *inclusive* of the
     * endpoints.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.TimeRange valid_for = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Common\V1\TimeRange $var
     * @return $this
     */
    public function setValidFor($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\TimeRange::class);
        $this->valid_for = $var;

        return $this;
    }

    /**
     * Specifies the name of the service operator. When selecting multiple
     * services, clients MUST use the operator to select services from
     * distinct operators. Operator MUST be formatted as a scheme-less
     * URI, e.g. sigstore.dev
     *
     * Generated from protobuf field <code>string operator = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Specifies the name of the service operator. When selecting multiple
     * services, clients MUST use the operator to select services from
     * distinct operators. Operator MUST be formatted as a scheme-less
     * URI, e.g. sigstore.dev
     *
     * Generated from protobuf field <code>string operator = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

}

