<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use UnexpectedValueException;

/**
 * ServiceSelector specifies how a client SHOULD select a set of
 * Services to connect to. A client SHOULD throw an error if
 * the value is SERVICE_SELECTOR_UNDEFINED.
 *
 * Protobuf type <code>dev.sigstore.trustroot.v1.ServiceSelector</code>
 */
class ServiceSelector
{
    /**
     * Generated from protobuf enum <code>SERVICE_SELECTOR_UNDEFINED = 0;</code>
     */
    const SERVICE_SELECTOR_UNDEFINED = 0;
    /**
     * Clients SHOULD select all Services based on supported API version
     * and validity window.
     *
     * Generated from protobuf enum <code>ALL = 1;</code>
     */
    const ALL = 1;
    /**
     * Clients SHOULD select one Service based on supported API version
     * and validity window. It is up to the client implementation to
     * decide how to select the Service, e.g. random or round-robin.
     *
     * Generated from protobuf enum <code>ANY = 2;</code>
     */
    const ANY = 2;
    /**
     * Clients SHOULD select a specific number of Services based on
     * supported API version and validity window, using the provided
     * `count`. It is up to the client implementation to decide how to
     * select the Service, e.g. random or round-robin.
     *
     * Generated from protobuf enum <code>EXACT = 3;</code>
     */
    const EXACT = 3;

    private static $valueToName = [
        self::SERVICE_SELECTOR_UNDEFINED => 'SERVICE_SELECTOR_UNDEFINED',
        self::ALL => 'ALL',
        self::ANY => 'ANY',
        self::EXACT => 'EXACT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

