<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SigningConfig represents the trusted entities/state needed by Sigstore
 * signing. In particular, it primarily contains service URLs that a Sigstore
 * signer may need to connect to for the online aspects of signing.
 *
 * Generated from protobuf message <code>dev.sigstore.trustroot.v1.SigningConfig</code>
 */
class SigningConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * MUST be application/vnd.dev.sigstore.signingconfig.v0.2+json
     * Clients MAY choose to also support
     * application/vnd.dev.sigstore.signingconfig.v0.1+json
     *
     * Generated from protobuf field <code>string media_type = 5;</code>
     */
    protected $media_type = '';
    /**
     * URLs to Fulcio-compatible CAs, capable of receiving
     * Certificate Signing Requests (CSRs) and responding with
     * issued certificates.
     * These URLs MUST be the "base" URL for the CAs, which clients
     * should construct an appropriate CSR endpoint on top of.
     * For example, if a CA URL is `https://example.com/ca`, then
     * the client MAY construct the CSR endpoint as
     * `https://example.com/ca/api/v2/signingCert`.
     * Clients MUST select only one Service with the highest API version
     * that the client is compatible with, that is within its
     * validity period, and has the newest validity start date.
     * Client SHOULD select the first Service that meets this requirement.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service ca_urls = 6;</code>
     */
    private $ca_urls;
    /**
     * URLs to OpenID Connect identity providers.
     * These URLs MUST be the "base" URLs for the OIDC IdPs, which clients
     * should perform well-known OpenID Connect discovery against.
     * Clients MUST select only one Service with the highest API version
     * that the client is compatible with, that is within its
     * validity period, and has the newest validity start date.
     * Client SHOULD select the first Service that meets this requirement.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service oidc_urls = 7;</code>
     */
    private $oidc_urls;
    /**
     * URLs to Rekor transparency logs.
     * These URL MUST be the "base" URLs for the transparency logs,
     * which clients should construct appropriate API endpoints on top of.
     * Clients MUST group Services by `operator` and select at most one
     * Service from each operator. Clients MUST select Services with the
     * highest API version that the client is compatible with, that are
     * within its validity period, and have the newest validity start dates.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     * Clients MUST select Services based on the selector value of
     * `rekor_tlog_config`.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service rekor_tlog_urls = 8;</code>
     */
    private $rekor_tlog_urls;
    /**
     * Specifies how a client should select the set of Rekor transparency
     * logs to write to.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceConfiguration rekor_tlog_config = 9;</code>
     */
    protected $rekor_tlog_config = null;
    /**
     * URLs to RFC 3161 Time Stamping Authorities (TSA).
     * These URLs MUST be the *full* URL for the TSA, meaning that it
     * should be suitable for submitting Time Stamp Requests (TSRs) to
     * via HTTP, per RFC 3161.
     * Clients MUST group Services by `operator` and select at most one
     * Service from each operator. Clients MUST select Services with the
     * highest API version that the client is compatible with, that are
     * within its validity period, and have the newest validity start dates.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     * Clients MUST select Services based on the selector value of
     * `tsa_config`.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service tsa_urls = 10;</code>
     */
    private $tsa_urls;
    /**
     * Specifies how a client should select the set of TSAs to request
     * signed timestamps from.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceConfiguration tsa_config = 11;</code>
     */
    protected $tsa_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $media_type
     *           MUST be application/vnd.dev.sigstore.signingconfig.v0.2+json
     *           Clients MAY choose to also support
     *           application/vnd.dev.sigstore.signingconfig.v0.1+json
     *     @type array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $ca_urls
     *           URLs to Fulcio-compatible CAs, capable of receiving
     *           Certificate Signing Requests (CSRs) and responding with
     *           issued certificates.
     *           These URLs MUST be the "base" URL for the CAs, which clients
     *           should construct an appropriate CSR endpoint on top of.
     *           For example, if a CA URL is `https://example.com/ca`, then
     *           the client MAY construct the CSR endpoint as
     *           `https://example.com/ca/api/v2/signingCert`.
     *           Clients MUST select only one Service with the highest API version
     *           that the client is compatible with, that is within its
     *           validity period, and has the newest validity start date.
     *           Client SHOULD select the first Service that meets this requirement.
     *           All listed Services SHOULD be sorted by the `valid_for` window in
     *           descending order, with the newest instance first.
     *     @type array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $oidc_urls
     *           URLs to OpenID Connect identity providers.
     *           These URLs MUST be the "base" URLs for the OIDC IdPs, which clients
     *           should perform well-known OpenID Connect discovery against.
     *           Clients MUST select only one Service with the highest API version
     *           that the client is compatible with, that is within its
     *           validity period, and has the newest validity start date.
     *           Client SHOULD select the first Service that meets this requirement.
     *           All listed Services SHOULD be sorted by the `valid_for` window in
     *           descending order, with the newest instance first.
     *     @type array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $rekor_tlog_urls
     *           URLs to Rekor transparency logs.
     *           These URL MUST be the "base" URLs for the transparency logs,
     *           which clients should construct appropriate API endpoints on top of.
     *           Clients MUST group Services by `operator` and select at most one
     *           Service from each operator. Clients MUST select Services with the
     *           highest API version that the client is compatible with, that are
     *           within its validity period, and have the newest validity start dates.
     *           All listed Services SHOULD be sorted by the `valid_for` window in
     *           descending order, with the newest instance first.
     *           Clients MUST select Services based on the selector value of
     *           `rekor_tlog_config`.
     *     @type \Dev\Sigstore\Trustroot\V1\ServiceConfiguration $rekor_tlog_config
     *           Specifies how a client should select the set of Rekor transparency
     *           logs to write to.
     *     @type array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $tsa_urls
     *           URLs to RFC 3161 Time Stamping Authorities (TSA).
     *           These URLs MUST be the *full* URL for the TSA, meaning that it
     *           should be suitable for submitting Time Stamp Requests (TSRs) to
     *           via HTTP, per RFC 3161.
     *           Clients MUST group Services by `operator` and select at most one
     *           Service from each operator. Clients MUST select Services with the
     *           highest API version that the client is compatible with, that are
     *           within its validity period, and have the newest validity start dates.
     *           All listed Services SHOULD be sorted by the `valid_for` window in
     *           descending order, with the newest instance first.
     *           Clients MUST select Services based on the selector value of
     *           `tsa_config`.
     *     @type \Dev\Sigstore\Trustroot\V1\ServiceConfiguration $tsa_config
     *           Specifies how a client should select the set of TSAs to request
     *           signed timestamps from.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreTrustroot::initOnce();
        parent::__construct($data);
    }

    /**
     * MUST be application/vnd.dev.sigstore.signingconfig.v0.2+json
     * Clients MAY choose to also support
     * application/vnd.dev.sigstore.signingconfig.v0.1+json
     *
     * Generated from protobuf field <code>string media_type = 5;</code>
     * @return string
     */
    public function getMediaType()
    {
        return $this->media_type;
    }

    /**
     * MUST be application/vnd.dev.sigstore.signingconfig.v0.2+json
     * Clients MAY choose to also support
     * application/vnd.dev.sigstore.signingconfig.v0.1+json
     *
     * Generated from protobuf field <code>string media_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->media_type = $var;

        return $this;
    }

    /**
     * URLs to Fulcio-compatible CAs, capable of receiving
     * Certificate Signing Requests (CSRs) and responding with
     * issued certificates.
     * These URLs MUST be the "base" URL for the CAs, which clients
     * should construct an appropriate CSR endpoint on top of.
     * For example, if a CA URL is `https://example.com/ca`, then
     * the client MAY construct the CSR endpoint as
     * `https://example.com/ca/api/v2/signingCert`.
     * Clients MUST select only one Service with the highest API version
     * that the client is compatible with, that is within its
     * validity period, and has the newest validity start date.
     * Client SHOULD select the first Service that meets this requirement.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service ca_urls = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCaUrls()
    {
        return $this->ca_urls;
    }

    /**
     * URLs to Fulcio-compatible CAs, capable of receiving
     * Certificate Signing Requests (CSRs) and responding with
     * issued certificates.
     * These URLs MUST be the "base" URL for the CAs, which clients
     * should construct an appropriate CSR endpoint on top of.
     * For example, if a CA URL is `https://example.com/ca`, then
     * the client MAY construct the CSR endpoint as
     * `https://example.com/ca/api/v2/signingCert`.
     * Clients MUST select only one Service with the highest API version
     * that the client is compatible with, that is within its
     * validity period, and has the newest validity start date.
     * Client SHOULD select the first Service that meets this requirement.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service ca_urls = 6;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCaUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\Service::class);
        $this->ca_urls = $arr;

        return $this;
    }

    /**
     * URLs to OpenID Connect identity providers.
     * These URLs MUST be the "base" URLs for the OIDC IdPs, which clients
     * should perform well-known OpenID Connect discovery against.
     * Clients MUST select only one Service with the highest API version
     * that the client is compatible with, that is within its
     * validity period, and has the newest validity start date.
     * Client SHOULD select the first Service that meets this requirement.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service oidc_urls = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOidcUrls()
    {
        return $this->oidc_urls;
    }

    /**
     * URLs to OpenID Connect identity providers.
     * These URLs MUST be the "base" URLs for the OIDC IdPs, which clients
     * should perform well-known OpenID Connect discovery against.
     * Clients MUST select only one Service with the highest API version
     * that the client is compatible with, that is within its
     * validity period, and has the newest validity start date.
     * Client SHOULD select the first Service that meets this requirement.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service oidc_urls = 7;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOidcUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\Service::class);
        $this->oidc_urls = $arr;

        return $this;
    }

    /**
     * URLs to Rekor transparency logs.
     * These URL MUST be the "base" URLs for the transparency logs,
     * which clients should construct appropriate API endpoints on top of.
     * Clients MUST group Services by `operator` and select at most one
     * Service from each operator. Clients MUST select Services with the
     * highest API version that the client is compatible with, that are
     * within its validity period, and have the newest validity start dates.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     * Clients MUST select Services based on the selector value of
     * `rekor_tlog_config`.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service rekor_tlog_urls = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRekorTlogUrls()
    {
        return $this->rekor_tlog_urls;
    }

    /**
     * URLs to Rekor transparency logs.
     * These URL MUST be the "base" URLs for the transparency logs,
     * which clients should construct appropriate API endpoints on top of.
     * Clients MUST group Services by `operator` and select at most one
     * Service from each operator. Clients MUST select Services with the
     * highest API version that the client is compatible with, that are
     * within its validity period, and have the newest validity start dates.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     * Clients MUST select Services based on the selector value of
     * `rekor_tlog_config`.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service rekor_tlog_urls = 8;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRekorTlogUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\Service::class);
        $this->rekor_tlog_urls = $arr;

        return $this;
    }

    /**
     * Specifies how a client should select the set of Rekor transparency
     * logs to write to.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceConfiguration rekor_tlog_config = 9;</code>
     * @return \Dev\Sigstore\Trustroot\V1\ServiceConfiguration|null
     */
    public function getRekorTlogConfig()
    {
        return $this->rekor_tlog_config;
    }

    public function hasRekorTlogConfig()
    {
        return isset($this->rekor_tlog_config);
    }

    public function clearRekorTlogConfig()
    {
        unset($this->rekor_tlog_config);
    }

    /**
     * Specifies how a client should select the set of Rekor transparency
     * logs to write to.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceConfiguration rekor_tlog_config = 9;</code>
     * @param \Dev\Sigstore\Trustroot\V1\ServiceConfiguration $var
     * @return $this
     */
    public function setRekorTlogConfig($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Trustroot\V1\ServiceConfiguration::class);
        $this->rekor_tlog_config = $var;

        return $this;
    }

    /**
     * URLs to RFC 3161 Time Stamping Authorities (TSA).
     * These URLs MUST be the *full* URL for the TSA, meaning that it
     * should be suitable for submitting Time Stamp Requests (TSRs) to
     * via HTTP, per RFC 3161.
     * Clients MUST group Services by `operator` and select at most one
     * Service from each operator. Clients MUST select Services with the
     * highest API version that the client is compatible with, that are
     * within its validity period, and have the newest validity start dates.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     * Clients MUST select Services based on the selector value of
     * `tsa_config`.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service tsa_urls = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTsaUrls()
    {
        return $this->tsa_urls;
    }

    /**
     * URLs to RFC 3161 Time Stamping Authorities (TSA).
     * These URLs MUST be the *full* URL for the TSA, meaning that it
     * should be suitable for submitting Time Stamp Requests (TSRs) to
     * via HTTP, per RFC 3161.
     * Clients MUST group Services by `operator` and select at most one
     * Service from each operator. Clients MUST select Services with the
     * highest API version that the client is compatible with, that are
     * within its validity period, and have the newest validity start dates.
     * All listed Services SHOULD be sorted by the `valid_for` window in
     * descending order, with the newest instance first.
     * Clients MUST select Services based on the selector value of
     * `tsa_config`.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.Service tsa_urls = 10;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\Service>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTsaUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\Service::class);
        $this->tsa_urls = $arr;

        return $this;
    }

    /**
     * Specifies how a client should select the set of TSAs to request
     * signed timestamps from.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceConfiguration tsa_config = 11;</code>
     * @return \Dev\Sigstore\Trustroot\V1\ServiceConfiguration|null
     */
    public function getTsaConfig()
    {
        return $this->tsa_config;
    }

    public function hasTsaConfig()
    {
        return isset($this->tsa_config);
    }

    public function clearTsaConfig()
    {
        unset($this->tsa_config);
    }

    /**
     * Specifies how a client should select the set of TSAs to request
     * signed timestamps from.
     *
     * Generated from protobuf field <code>.dev.sigstore.trustroot.v1.ServiceConfiguration tsa_config = 11;</code>
     * @param \Dev\Sigstore\Trustroot\V1\ServiceConfiguration $var
     * @return $this
     */
    public function setTsaConfig($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Trustroot\V1\ServiceConfiguration::class);
        $this->tsa_config = $var;

        return $this;
    }

}

