<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TransparencyLogInstance describes the immutable parameters from a
 * transparency log.
 * See https://www.rfc-editor.org/rfc/rfc9162.html#name-log-parameters
 * for more details.
 * The included parameters are the minimal set required to identify a log,
 * and verify an inclusion proof/promise.
 *
 * Generated from protobuf message <code>dev.sigstore.trustroot.v1.TransparencyLogInstance</code>
 */
class TransparencyLogInstance extends \Google\Protobuf\Internal\Message
{
    /**
     * The base URL at which can be used to URLs for the client.
     * SHOULD match the origin on the log checkpoint:
     * https://github.com/C2SP/C2SP/blob/main/tlog-checkpoint.md#note-text.
     *
     * Generated from protobuf field <code>string base_url = 1;</code>
     */
    protected $base_url = '';
    /**
     * The hash algorithm used for the Merkle Tree.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashAlgorithm hash_algorithm = 2;</code>
     */
    protected $hash_algorithm = 0;
    /**
     * The public key used to verify signatures generated by the log.
     * This attribute contains the signature algorithm used by the log.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKey public_key = 3;</code>
     */
    protected $public_key = null;
    /**
     * The identifier for this transparency log.
     * Represented as the SHA-256 hash of the log's public key,
     * calculated over the DER encoding of the key represented as
     * SubjectPublicKeyInfo.
     * See https://www.rfc-editor.org/rfc/rfc6962#section-3.2
     * For Rekor v2 instances, log_id and checkpoint_key_id will be set
     * to the same value.
     * It is recommended to use checkpoint_key_id instead, since log_id is not
     * guaranteed to be unique across multiple deployments. Clients
     * must use the key name and key ID, as defined by the signed-note spec
     * linked below, from a checkpoint to determine the correct
     * TransparencyLogInstance to verify a proof.
     * log_id will eventually be deprecated in favor of checkpoint_id.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId log_id = 4;</code>
     */
    protected $log_id = null;
    /**
     * The unique identifier for the log, used in the checkpoint.
     * Only supported for TrustedRoot media types matching or greater than
     * application/vnd.dev.sigstore.trustedroot.v0.2+json
     * Its calculation is described in
     * https://github.com/C2SP/C2SP/blob/main/signed-note.md#signatures
     * SHOULD be set for all logs. When not set, clients MUST use log_id.
     * For Ed25519 signatures, the key ID is computed per the C2SP spec:
     * key ID = SHA-256(key name || 0x0A || 0x01 || 32-byte Ed25519 public key)[:4]
     * For ECDSA signatures, the key ID is computed per the C2SP spec:
     * key ID = SHA-256(PKIX ASN.1 DER-encoded public key, in SubjectPublicKeyInfo format)[:4]
     * For RSA signatures, the signature type will be 0xff with an appended identifier for the format,
     * "PKIX-RSA-PKCS#1v1.5":
     * key ID = SHA-256(key name || 0x0A || 0xff || PKIX-RSA-PKCS#1v1.5 || PKIX ASN.1 DER-encoded public key)[:4]
     * This is provided for convenience. Clients can also calculate the
     * checkpoint key ID given the log's public key.
     * SHOULD be 4 bytes long, as a truncated hash.
     * To find a matching TransparencyLogInstance in the TrustedRoot,
     * clients will parse the checkpoint, and for each signature line,
     * use the key name (i.e. log origin, base_url from TrustedRoot)
     * and checkpoint key ID (i.e. checkpoint_key_id from TrustedRoot)
     * which can then be compared against the TrustedRoot log instances.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId checkpoint_key_id = 5;</code>
     */
    protected $checkpoint_key_id = null;
    /**
     * The name of the operator of this log deployment. Operator MUST be
     * formatted as a scheme-less URI, e.g. sigstore.dev
     * Only supported for TrustedRoot media types matching or greater than
     * application/vnd.dev.sigstore.trustedroot.v0.2+json
     * This MUST be used when there are multiple transparency log instances
     * to determine if log proof verification meets a specified threshold,
     * e.g. two proofs from log deployments operated by the same operator
     * should count as only one valid proof.
     *
     * Generated from protobuf field <code>string operator = 6;</code>
     */
    protected $operator = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $base_url
     *           The base URL at which can be used to URLs for the client.
     *           SHOULD match the origin on the log checkpoint:
     *           https://github.com/C2SP/C2SP/blob/main/tlog-checkpoint.md#note-text.
     *     @type int $hash_algorithm
     *           The hash algorithm used for the Merkle Tree.
     *     @type \Dev\Sigstore\Common\V1\PublicKey $public_key
     *           The public key used to verify signatures generated by the log.
     *           This attribute contains the signature algorithm used by the log.
     *     @type \Dev\Sigstore\Common\V1\LogId $log_id
     *           The identifier for this transparency log.
     *           Represented as the SHA-256 hash of the log's public key,
     *           calculated over the DER encoding of the key represented as
     *           SubjectPublicKeyInfo.
     *           See https://www.rfc-editor.org/rfc/rfc6962#section-3.2
     *           For Rekor v2 instances, log_id and checkpoint_key_id will be set
     *           to the same value.
     *           It is recommended to use checkpoint_key_id instead, since log_id is not
     *           guaranteed to be unique across multiple deployments. Clients
     *           must use the key name and key ID, as defined by the signed-note spec
     *           linked below, from a checkpoint to determine the correct
     *           TransparencyLogInstance to verify a proof.
     *           log_id will eventually be deprecated in favor of checkpoint_id.
     *     @type \Dev\Sigstore\Common\V1\LogId $checkpoint_key_id
     *           The unique identifier for the log, used in the checkpoint.
     *           Only supported for TrustedRoot media types matching or greater than
     *           application/vnd.dev.sigstore.trustedroot.v0.2+json
     *           Its calculation is described in
     *           https://github.com/C2SP/C2SP/blob/main/signed-note.md#signatures
     *           SHOULD be set for all logs. When not set, clients MUST use log_id.
     *           For Ed25519 signatures, the key ID is computed per the C2SP spec:
     *           key ID = SHA-256(key name || 0x0A || 0x01 || 32-byte Ed25519 public key)[:4]
     *           For ECDSA signatures, the key ID is computed per the C2SP spec:
     *           key ID = SHA-256(PKIX ASN.1 DER-encoded public key, in SubjectPublicKeyInfo format)[:4]
     *           For RSA signatures, the signature type will be 0xff with an appended identifier for the format,
     *           "PKIX-RSA-PKCS#1v1.5":
     *           key ID = SHA-256(key name || 0x0A || 0xff || PKIX-RSA-PKCS#1v1.5 || PKIX ASN.1 DER-encoded public key)[:4]
     *           This is provided for convenience. Clients can also calculate the
     *           checkpoint key ID given the log's public key.
     *           SHOULD be 4 bytes long, as a truncated hash.
     *           To find a matching TransparencyLogInstance in the TrustedRoot,
     *           clients will parse the checkpoint, and for each signature line,
     *           use the key name (i.e. log origin, base_url from TrustedRoot)
     *           and checkpoint key ID (i.e. checkpoint_key_id from TrustedRoot)
     *           which can then be compared against the TrustedRoot log instances.
     *     @type string $operator
     *           The name of the operator of this log deployment. Operator MUST be
     *           formatted as a scheme-less URI, e.g. sigstore.dev
     *           Only supported for TrustedRoot media types matching or greater than
     *           application/vnd.dev.sigstore.trustedroot.v0.2+json
     *           This MUST be used when there are multiple transparency log instances
     *           to determine if log proof verification meets a specified threshold,
     *           e.g. two proofs from log deployments operated by the same operator
     *           should count as only one valid proof.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreTrustroot::initOnce();
        parent::__construct($data);
    }

    /**
     * The base URL at which can be used to URLs for the client.
     * SHOULD match the origin on the log checkpoint:
     * https://github.com/C2SP/C2SP/blob/main/tlog-checkpoint.md#note-text.
     *
     * Generated from protobuf field <code>string base_url = 1;</code>
     * @return string
     */
    public function getBaseUrl()
    {
        return $this->base_url;
    }

    /**
     * The base URL at which can be used to URLs for the client.
     * SHOULD match the origin on the log checkpoint:
     * https://github.com/C2SP/C2SP/blob/main/tlog-checkpoint.md#note-text.
     *
     * Generated from protobuf field <code>string base_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->base_url = $var;

        return $this;
    }

    /**
     * The hash algorithm used for the Merkle Tree.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashAlgorithm hash_algorithm = 2;</code>
     * @return int
     */
    public function getHashAlgorithm()
    {
        return $this->hash_algorithm;
    }

    /**
     * The hash algorithm used for the Merkle Tree.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.HashAlgorithm hash_algorithm = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHashAlgorithm($var)
    {
        GPBUtil::checkEnum($var, \Dev\Sigstore\Common\V1\HashAlgorithm::class);
        $this->hash_algorithm = $var;

        return $this;
    }

    /**
     * The public key used to verify signatures generated by the log.
     * This attribute contains the signature algorithm used by the log.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKey public_key = 3;</code>
     * @return \Dev\Sigstore\Common\V1\PublicKey|null
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    public function hasPublicKey()
    {
        return isset($this->public_key);
    }

    public function clearPublicKey()
    {
        unset($this->public_key);
    }

    /**
     * The public key used to verify signatures generated by the log.
     * This attribute contains the signature algorithm used by the log.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKey public_key = 3;</code>
     * @param \Dev\Sigstore\Common\V1\PublicKey $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\PublicKey::class);
        $this->public_key = $var;

        return $this;
    }

    /**
     * The identifier for this transparency log.
     * Represented as the SHA-256 hash of the log's public key,
     * calculated over the DER encoding of the key represented as
     * SubjectPublicKeyInfo.
     * See https://www.rfc-editor.org/rfc/rfc6962#section-3.2
     * For Rekor v2 instances, log_id and checkpoint_key_id will be set
     * to the same value.
     * It is recommended to use checkpoint_key_id instead, since log_id is not
     * guaranteed to be unique across multiple deployments. Clients
     * must use the key name and key ID, as defined by the signed-note spec
     * linked below, from a checkpoint to determine the correct
     * TransparencyLogInstance to verify a proof.
     * log_id will eventually be deprecated in favor of checkpoint_id.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId log_id = 4;</code>
     * @return \Dev\Sigstore\Common\V1\LogId|null
     */
    public function getLogId()
    {
        return $this->log_id;
    }

    public function hasLogId()
    {
        return isset($this->log_id);
    }

    public function clearLogId()
    {
        unset($this->log_id);
    }

    /**
     * The identifier for this transparency log.
     * Represented as the SHA-256 hash of the log's public key,
     * calculated over the DER encoding of the key represented as
     * SubjectPublicKeyInfo.
     * See https://www.rfc-editor.org/rfc/rfc6962#section-3.2
     * For Rekor v2 instances, log_id and checkpoint_key_id will be set
     * to the same value.
     * It is recommended to use checkpoint_key_id instead, since log_id is not
     * guaranteed to be unique across multiple deployments. Clients
     * must use the key name and key ID, as defined by the signed-note spec
     * linked below, from a checkpoint to determine the correct
     * TransparencyLogInstance to verify a proof.
     * log_id will eventually be deprecated in favor of checkpoint_id.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId log_id = 4;</code>
     * @param \Dev\Sigstore\Common\V1\LogId $var
     * @return $this
     */
    public function setLogId($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\LogId::class);
        $this->log_id = $var;

        return $this;
    }

    /**
     * The unique identifier for the log, used in the checkpoint.
     * Only supported for TrustedRoot media types matching or greater than
     * application/vnd.dev.sigstore.trustedroot.v0.2+json
     * Its calculation is described in
     * https://github.com/C2SP/C2SP/blob/main/signed-note.md#signatures
     * SHOULD be set for all logs. When not set, clients MUST use log_id.
     * For Ed25519 signatures, the key ID is computed per the C2SP spec:
     * key ID = SHA-256(key name || 0x0A || 0x01 || 32-byte Ed25519 public key)[:4]
     * For ECDSA signatures, the key ID is computed per the C2SP spec:
     * key ID = SHA-256(PKIX ASN.1 DER-encoded public key, in SubjectPublicKeyInfo format)[:4]
     * For RSA signatures, the signature type will be 0xff with an appended identifier for the format,
     * "PKIX-RSA-PKCS#1v1.5":
     * key ID = SHA-256(key name || 0x0A || 0xff || PKIX-RSA-PKCS#1v1.5 || PKIX ASN.1 DER-encoded public key)[:4]
     * This is provided for convenience. Clients can also calculate the
     * checkpoint key ID given the log's public key.
     * SHOULD be 4 bytes long, as a truncated hash.
     * To find a matching TransparencyLogInstance in the TrustedRoot,
     * clients will parse the checkpoint, and for each signature line,
     * use the key name (i.e. log origin, base_url from TrustedRoot)
     * and checkpoint key ID (i.e. checkpoint_key_id from TrustedRoot)
     * which can then be compared against the TrustedRoot log instances.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId checkpoint_key_id = 5;</code>
     * @return \Dev\Sigstore\Common\V1\LogId|null
     */
    public function getCheckpointKeyId()
    {
        return $this->checkpoint_key_id;
    }

    public function hasCheckpointKeyId()
    {
        return isset($this->checkpoint_key_id);
    }

    public function clearCheckpointKeyId()
    {
        unset($this->checkpoint_key_id);
    }

    /**
     * The unique identifier for the log, used in the checkpoint.
     * Only supported for TrustedRoot media types matching or greater than
     * application/vnd.dev.sigstore.trustedroot.v0.2+json
     * Its calculation is described in
     * https://github.com/C2SP/C2SP/blob/main/signed-note.md#signatures
     * SHOULD be set for all logs. When not set, clients MUST use log_id.
     * For Ed25519 signatures, the key ID is computed per the C2SP spec:
     * key ID = SHA-256(key name || 0x0A || 0x01 || 32-byte Ed25519 public key)[:4]
     * For ECDSA signatures, the key ID is computed per the C2SP spec:
     * key ID = SHA-256(PKIX ASN.1 DER-encoded public key, in SubjectPublicKeyInfo format)[:4]
     * For RSA signatures, the signature type will be 0xff with an appended identifier for the format,
     * "PKIX-RSA-PKCS#1v1.5":
     * key ID = SHA-256(key name || 0x0A || 0xff || PKIX-RSA-PKCS#1v1.5 || PKIX ASN.1 DER-encoded public key)[:4]
     * This is provided for convenience. Clients can also calculate the
     * checkpoint key ID given the log's public key.
     * SHOULD be 4 bytes long, as a truncated hash.
     * To find a matching TransparencyLogInstance in the TrustedRoot,
     * clients will parse the checkpoint, and for each signature line,
     * use the key name (i.e. log origin, base_url from TrustedRoot)
     * and checkpoint key ID (i.e. checkpoint_key_id from TrustedRoot)
     * which can then be compared against the TrustedRoot log instances.
     *
     * Generated from protobuf field <code>.dev.sigstore.common.v1.LogId checkpoint_key_id = 5;</code>
     * @param \Dev\Sigstore\Common\V1\LogId $var
     * @return $this
     */
    public function setCheckpointKeyId($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\LogId::class);
        $this->checkpoint_key_id = $var;

        return $this;
    }

    /**
     * The name of the operator of this log deployment. Operator MUST be
     * formatted as a scheme-less URI, e.g. sigstore.dev
     * Only supported for TrustedRoot media types matching or greater than
     * application/vnd.dev.sigstore.trustedroot.v0.2+json
     * This MUST be used when there are multiple transparency log instances
     * to determine if log proof verification meets a specified threshold,
     * e.g. two proofs from log deployments operated by the same operator
     * should count as only one valid proof.
     *
     * Generated from protobuf field <code>string operator = 6;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * The name of the operator of this log deployment. Operator MUST be
     * formatted as a scheme-less URI, e.g. sigstore.dev
     * Only supported for TrustedRoot media types matching or greater than
     * application/vnd.dev.sigstore.trustedroot.v0.2+json
     * This MUST be used when there are multiple transparency log instances
     * to determine if log proof verification meets a specified threshold,
     * e.g. two proofs from log deployments operated by the same operator
     * should count as only one valid proof.
     *
     * Generated from protobuf field <code>string operator = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

}

