<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_trustroot.proto

namespace Dev\Sigstore\Trustroot\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TrustedRoot describes the client's complete set of trusted entities.
 * How the TrustedRoot is populated is not specified, but can be a
 * combination of many sources such as TUF repositories, files on disk etc.
 * The TrustedRoot is not meant to be used for any artifact verification, only
 * to capture the complete/global set of trusted verification materials.
 * When verifying an artifact, based on the artifact and policies, a selection
 * of keys/authorities are expected to be extracted and provided to the
 * verification function. This way the set of keys/authorities can be kept to
 * a minimal set by the policy to gain better control over what signatures
 * that are allowed.
 * The embedded transparency logs, CT logs, CAs and TSAs MUST include any
 * previously used instance -- otherwise signatures made in the past cannot
 * be verified.
 * All the listed instances SHOULD be sorted by the 'valid_for.start'
 * in ascending order, that is, the oldest instance first. Clients
 * MUST accept instances that overlaps in time, if not clients may
 * experience problems during rotations of verification materials.
 * To be able to manage planned rotations of either transparency logs or
 * certificate authorities, clienst MUST accept lists of instances where
 * the last instance have a 'valid_for' that belongs to the future.
 * This should not be a problem as clients SHOULD first seek the trust root
 * for a suitable instance before creating a per artifact trust root (that
 * is, a sub-set of the complete trust root) that is used for verification.
 *
 * Generated from protobuf message <code>dev.sigstore.trustroot.v1.TrustedRoot</code>
 */
class TrustedRoot extends \Google\Protobuf\Internal\Message
{
    /**
     * MUST be application/vnd.dev.sigstore.trustedroot.v0.2+json
     * when encoded as JSON.
     * Clients MAY choose to also support
     * application/vnd.dev.sigstore.trustedroot.v0.1+json
     * Clients MAY process and parse content with the media type defined
     * in the old format:
     * application/vnd.dev.sigstore.trustedroot+json;version=0.1
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     */
    protected $media_type = '';
    /**
     * A set of trusted Rekor servers.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.TransparencyLogInstance tlogs = 2;</code>
     */
    private $tlogs;
    /**
     * A set of trusted certificate authorities (e.g Fulcio), and any
     * intermediate certificates they provide.
     * If a CA is issuing multiple intermediate certificate, each
     * combination shall be represented as separate chain. I.e, a single
     * root cert may appear in multiple chains but with different
     * intermediate and/or leaf certificates.
     * The certificates are intended to be used for verifying artifact
     * signatures.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.CertificateAuthority certificate_authorities = 3;</code>
     */
    private $certificate_authorities;
    /**
     * A set of trusted certificate transparency logs.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.TransparencyLogInstance ctlogs = 4;</code>
     */
    private $ctlogs;
    /**
     * A set of trusted timestamping authorities.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.CertificateAuthority timestamp_authorities = 5;</code>
     */
    private $timestamp_authorities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $media_type
     *           MUST be application/vnd.dev.sigstore.trustedroot.v0.2+json
     *           when encoded as JSON.
     *           Clients MAY choose to also support
     *           application/vnd.dev.sigstore.trustedroot.v0.1+json
     *           Clients MAY process and parse content with the media type defined
     *           in the old format:
     *           application/vnd.dev.sigstore.trustedroot+json;version=0.1
     *     @type array<\Dev\Sigstore\Trustroot\V1\TransparencyLogInstance>|\Google\Protobuf\Internal\RepeatedField $tlogs
     *           A set of trusted Rekor servers.
     *     @type array<\Dev\Sigstore\Trustroot\V1\CertificateAuthority>|\Google\Protobuf\Internal\RepeatedField $certificate_authorities
     *           A set of trusted certificate authorities (e.g Fulcio), and any
     *           intermediate certificates they provide.
     *           If a CA is issuing multiple intermediate certificate, each
     *           combination shall be represented as separate chain. I.e, a single
     *           root cert may appear in multiple chains but with different
     *           intermediate and/or leaf certificates.
     *           The certificates are intended to be used for verifying artifact
     *           signatures.
     *     @type array<\Dev\Sigstore\Trustroot\V1\TransparencyLogInstance>|\Google\Protobuf\Internal\RepeatedField $ctlogs
     *           A set of trusted certificate transparency logs.
     *     @type array<\Dev\Sigstore\Trustroot\V1\CertificateAuthority>|\Google\Protobuf\Internal\RepeatedField $timestamp_authorities
     *           A set of trusted timestamping authorities.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreTrustroot::initOnce();
        parent::__construct($data);
    }

    /**
     * MUST be application/vnd.dev.sigstore.trustedroot.v0.2+json
     * when encoded as JSON.
     * Clients MAY choose to also support
     * application/vnd.dev.sigstore.trustedroot.v0.1+json
     * Clients MAY process and parse content with the media type defined
     * in the old format:
     * application/vnd.dev.sigstore.trustedroot+json;version=0.1
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     * @return string
     */
    public function getMediaType()
    {
        return $this->media_type;
    }

    /**
     * MUST be application/vnd.dev.sigstore.trustedroot.v0.2+json
     * when encoded as JSON.
     * Clients MAY choose to also support
     * application/vnd.dev.sigstore.trustedroot.v0.1+json
     * Clients MAY process and parse content with the media type defined
     * in the old format:
     * application/vnd.dev.sigstore.trustedroot+json;version=0.1
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->media_type = $var;

        return $this;
    }

    /**
     * A set of trusted Rekor servers.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.TransparencyLogInstance tlogs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTlogs()
    {
        return $this->tlogs;
    }

    /**
     * A set of trusted Rekor servers.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.TransparencyLogInstance tlogs = 2;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\TransparencyLogInstance>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTlogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\TransparencyLogInstance::class);
        $this->tlogs = $arr;

        return $this;
    }

    /**
     * A set of trusted certificate authorities (e.g Fulcio), and any
     * intermediate certificates they provide.
     * If a CA is issuing multiple intermediate certificate, each
     * combination shall be represented as separate chain. I.e, a single
     * root cert may appear in multiple chains but with different
     * intermediate and/or leaf certificates.
     * The certificates are intended to be used for verifying artifact
     * signatures.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.CertificateAuthority certificate_authorities = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificateAuthorities()
    {
        return $this->certificate_authorities;
    }

    /**
     * A set of trusted certificate authorities (e.g Fulcio), and any
     * intermediate certificates they provide.
     * If a CA is issuing multiple intermediate certificate, each
     * combination shall be represented as separate chain. I.e, a single
     * root cert may appear in multiple chains but with different
     * intermediate and/or leaf certificates.
     * The certificates are intended to be used for verifying artifact
     * signatures.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.CertificateAuthority certificate_authorities = 3;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\CertificateAuthority>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificateAuthorities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\CertificateAuthority::class);
        $this->certificate_authorities = $arr;

        return $this;
    }

    /**
     * A set of trusted certificate transparency logs.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.TransparencyLogInstance ctlogs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCtlogs()
    {
        return $this->ctlogs;
    }

    /**
     * A set of trusted certificate transparency logs.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.TransparencyLogInstance ctlogs = 4;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\TransparencyLogInstance>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCtlogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\TransparencyLogInstance::class);
        $this->ctlogs = $arr;

        return $this;
    }

    /**
     * A set of trusted timestamping authorities.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.CertificateAuthority timestamp_authorities = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimestampAuthorities()
    {
        return $this->timestamp_authorities;
    }

    /**
     * A set of trusted timestamping authorities.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.trustroot.v1.CertificateAuthority timestamp_authorities = 5;</code>
     * @param array<\Dev\Sigstore\Trustroot\V1\CertificateAuthority>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimestampAuthorities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Trustroot\V1\CertificateAuthority::class);
        $this->timestamp_authorities = $arr;

        return $this;
    }

}

