<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1\ArtifactVerificationOptions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.verification.v1.ArtifactVerificationOptions.ObserverTimestampOptions</code>
 */
class ObserverTimestampOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * The number of external observers of the timestamp.
     * This is a union of RFC3161 signed timestamps, and
     * integrated timestamps from a transparency log, that
     * could include additional timestamp sources in the
     * future.
     *
     * Generated from protobuf field <code>int32 threshold = 1;</code>
     */
    protected $threshold = 0;
    /**
     * Disable observer timestamp verification.
     *
     * Generated from protobuf field <code>bool disable = 2;</code>
     */
    protected $disable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $threshold
     *           The number of external observers of the timestamp.
     *           This is a union of RFC3161 signed timestamps, and
     *           integrated timestamps from a transparency log, that
     *           could include additional timestamp sources in the
     *           future.
     *     @type bool $disable
     *           Disable observer timestamp verification.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * The number of external observers of the timestamp.
     * This is a union of RFC3161 signed timestamps, and
     * integrated timestamps from a transparency log, that
     * could include additional timestamp sources in the
     * future.
     *
     * Generated from protobuf field <code>int32 threshold = 1;</code>
     * @return int
     */
    public function getThreshold()
    {
        return $this->threshold;
    }

    /**
     * The number of external observers of the timestamp.
     * This is a union of RFC3161 signed timestamps, and
     * integrated timestamps from a transparency log, that
     * could include additional timestamp sources in the
     * future.
     *
     * Generated from protobuf field <code>int32 threshold = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setThreshold($var)
    {
        GPBUtil::checkInt32($var);
        $this->threshold = $var;

        return $this;
    }

    /**
     * Disable observer timestamp verification.
     *
     * Generated from protobuf field <code>bool disable = 2;</code>
     * @return bool
     */
    public function getDisable()
    {
        return $this->disable;
    }

    /**
     * Disable observer timestamp verification.
     *
     * Generated from protobuf field <code>bool disable = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisable($var)
    {
        GPBUtil::checkBool($var);
        $this->disable = $var;

        return $this;
    }

}

