<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_verification.proto

namespace Dev\Sigstore\Verification\V1\ArtifactVerificationOptions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.verification.v1.ArtifactVerificationOptions.TlogOptions</code>
 */
class TlogOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Number of transparency logs the entry must appear on.
     *
     * Generated from protobuf field <code>int32 threshold = 1;</code>
     */
    protected $threshold = 0;
    /**
     * Perform an online inclusion proof.
     *
     * Generated from protobuf field <code>bool perform_online_verification = 2;</code>
     */
    protected $perform_online_verification = false;
    /**
     * Disable verification for transparency logs.
     *
     * Generated from protobuf field <code>bool disable = 3;</code>
     */
    protected $disable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $threshold
     *           Number of transparency logs the entry must appear on.
     *     @type bool $perform_online_verification
     *           Perform an online inclusion proof.
     *     @type bool $disable
     *           Disable verification for transparency logs.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreVerification::initOnce();
        parent::__construct($data);
    }

    /**
     * Number of transparency logs the entry must appear on.
     *
     * Generated from protobuf field <code>int32 threshold = 1;</code>
     * @return int
     */
    public function getThreshold()
    {
        return $this->threshold;
    }

    /**
     * Number of transparency logs the entry must appear on.
     *
     * Generated from protobuf field <code>int32 threshold = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setThreshold($var)
    {
        GPBUtil::checkInt32($var);
        $this->threshold = $var;

        return $this;
    }

    /**
     * Perform an online inclusion proof.
     *
     * Generated from protobuf field <code>bool perform_online_verification = 2;</code>
     * @return bool
     */
    public function getPerformOnlineVerification()
    {
        return $this->perform_online_verification;
    }

    /**
     * Perform an online inclusion proof.
     *
     * Generated from protobuf field <code>bool perform_online_verification = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setPerformOnlineVerification($var)
    {
        GPBUtil::checkBool($var);
        $this->perform_online_verification = $var;

        return $this;
    }

    /**
     * Disable verification for transparency logs.
     *
     * Generated from protobuf field <code>bool disable = 3;</code>
     * @return bool
     */
    public function getDisable()
    {
        return $this->disable;
    }

    /**
     * Disable verification for transparency logs.
     *
     * Generated from protobuf field <code>bool disable = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisable($var)
    {
        GPBUtil::checkBool($var);
        $this->disable = $var;

        return $this;
    }

}

