<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_bundle.proto

namespace Dev\Sigstore\Bundle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dev.sigstore.bundle.v1.Bundle</code>
 */
class Bundle extends \Google\Protobuf\Internal\Message
{
    /**
     * MUST be application/vnd.dev.sigstore.bundle.v0.3+json when
     * when encoded as JSON.
     * Clients must to be able to accept media type using the previously
     * defined formats:
     * * application/vnd.dev.sigstore.bundle+json;version=0.1
     * * application/vnd.dev.sigstore.bundle+json;version=0.2
     * * application/vnd.dev.sigstore.bundle+json;version=0.3
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     */
    protected $media_type = '';
    /**
     * When a signer is identified by a X.509 certificate, a verifier MUST
     * verify that the signature was computed at the time the certificate
     * was valid as described in the Sigstore client spec: "Verification
     * using a Bundle".
     * <https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#heading=h.x8bduppe89ln>
     * If the verification material contains a public key identifier
     * (key hint) and the `content` is a DSSE envelope, the key hints
     * MUST be exactly the same in the verification material and in the
     * DSSE envelope.
     *
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.VerificationMaterial verification_material = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $verification_material = null;
    protected $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $media_type
     *           MUST be application/vnd.dev.sigstore.bundle.v0.3+json when
     *           when encoded as JSON.
     *           Clients must to be able to accept media type using the previously
     *           defined formats:
     *           * application/vnd.dev.sigstore.bundle+json;version=0.1
     *           * application/vnd.dev.sigstore.bundle+json;version=0.2
     *           * application/vnd.dev.sigstore.bundle+json;version=0.3
     *     @type \Dev\Sigstore\Bundle\V1\VerificationMaterial $verification_material
     *           When a signer is identified by a X.509 certificate, a verifier MUST
     *           verify that the signature was computed at the time the certificate
     *           was valid as described in the Sigstore client spec: "Verification
     *           using a Bundle".
     *           <https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#heading=h.x8bduppe89ln>
     *           If the verification material contains a public key identifier
     *           (key hint) and the `content` is a DSSE envelope, the key hints
     *           MUST be exactly the same in the verification material and in the
     *           DSSE envelope.
     *     @type \Dev\Sigstore\Common\V1\MessageSignature $message_signature
     *     @type \Io\Intoto\Envelope $dsse_envelope
     *           A DSSE envelope can contain arbitrary payloads.
     *           Verifiers must verify that the payload type is a
     *           supported and expected type. This is part of the DSSE
     *           protocol which is defined here:
     *           <https://github.com/secure-systems-lab/dsse/blob/master/protocol.md>
     *           DSSE envelopes in a bundle MUST have exactly one signature.
     *           This is a limitation from the DSSE spec, as it can contain
     *           multiple signatures. There are two primary reasons:
     *           1. It simplifies the verification logic and policy
     *           2. The bundle (currently) can only contain a single
     *              instance of the required verification materials
     *           During verification a client MUST reject an envelope if
     *           the number of signatures is not equal to one.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreBundle::initOnce();
        parent::__construct($data);
    }

    /**
     * MUST be application/vnd.dev.sigstore.bundle.v0.3+json when
     * when encoded as JSON.
     * Clients must to be able to accept media type using the previously
     * defined formats:
     * * application/vnd.dev.sigstore.bundle+json;version=0.1
     * * application/vnd.dev.sigstore.bundle+json;version=0.2
     * * application/vnd.dev.sigstore.bundle+json;version=0.3
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     * @return string
     */
    public function getMediaType()
    {
        return $this->media_type;
    }

    /**
     * MUST be application/vnd.dev.sigstore.bundle.v0.3+json when
     * when encoded as JSON.
     * Clients must to be able to accept media type using the previously
     * defined formats:
     * * application/vnd.dev.sigstore.bundle+json;version=0.1
     * * application/vnd.dev.sigstore.bundle+json;version=0.2
     * * application/vnd.dev.sigstore.bundle+json;version=0.3
     *
     * Generated from protobuf field <code>string media_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->media_type = $var;

        return $this;
    }

    /**
     * When a signer is identified by a X.509 certificate, a verifier MUST
     * verify that the signature was computed at the time the certificate
     * was valid as described in the Sigstore client spec: "Verification
     * using a Bundle".
     * <https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#heading=h.x8bduppe89ln>
     * If the verification material contains a public key identifier
     * (key hint) and the `content` is a DSSE envelope, the key hints
     * MUST be exactly the same in the verification material and in the
     * DSSE envelope.
     *
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.VerificationMaterial verification_material = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Bundle\V1\VerificationMaterial|null
     */
    public function getVerificationMaterial()
    {
        return $this->verification_material;
    }

    public function hasVerificationMaterial()
    {
        return isset($this->verification_material);
    }

    public function clearVerificationMaterial()
    {
        unset($this->verification_material);
    }

    /**
     * When a signer is identified by a X.509 certificate, a verifier MUST
     * verify that the signature was computed at the time the certificate
     * was valid as described in the Sigstore client spec: "Verification
     * using a Bundle".
     * <https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#heading=h.x8bduppe89ln>
     * If the verification material contains a public key identifier
     * (key hint) and the `content` is a DSSE envelope, the key hints
     * MUST be exactly the same in the verification material and in the
     * DSSE envelope.
     *
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.VerificationMaterial verification_material = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Bundle\V1\VerificationMaterial $var
     * @return $this
     */
    public function setVerificationMaterial($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Bundle\V1\VerificationMaterial::class);
        $this->verification_material = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.MessageSignature message_signature = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Common\V1\MessageSignature|null
     */
    public function getMessageSignature()
    {
        return $this->readOneof(3);
    }

    public function hasMessageSignature()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.MessageSignature message_signature = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Common\V1\MessageSignature $var
     * @return $this
     */
    public function setMessageSignature($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\MessageSignature::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * A DSSE envelope can contain arbitrary payloads.
     * Verifiers must verify that the payload type is a
     * supported and expected type. This is part of the DSSE
     * protocol which is defined here:
     * <https://github.com/secure-systems-lab/dsse/blob/master/protocol.md>
     * DSSE envelopes in a bundle MUST have exactly one signature.
     * This is a limitation from the DSSE spec, as it can contain
     * multiple signatures. There are two primary reasons:
     * 1. It simplifies the verification logic and policy
     * 2. The bundle (currently) can only contain a single
     *    instance of the required verification materials
     * During verification a client MUST reject an envelope if
     * the number of signatures is not equal to one.
     *
     * Generated from protobuf field <code>.io.intoto.Envelope dsse_envelope = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Io\Intoto\Envelope|null
     */
    public function getDsseEnvelope()
    {
        return $this->readOneof(4);
    }

    public function hasDsseEnvelope()
    {
        return $this->hasOneof(4);
    }

    /**
     * A DSSE envelope can contain arbitrary payloads.
     * Verifiers must verify that the payload type is a
     * supported and expected type. This is part of the DSSE
     * protocol which is defined here:
     * <https://github.com/secure-systems-lab/dsse/blob/master/protocol.md>
     * DSSE envelopes in a bundle MUST have exactly one signature.
     * This is a limitation from the DSSE spec, as it can contain
     * multiple signatures. There are two primary reasons:
     * 1. It simplifies the verification logic and policy
     * 2. The bundle (currently) can only contain a single
     *    instance of the required verification materials
     * During verification a client MUST reject an envelope if
     * the number of signatures is not equal to one.
     *
     * Generated from protobuf field <code>.io.intoto.Envelope dsse_envelope = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Io\Intoto\Envelope $var
     * @return $this
     */
    public function setDsseEnvelope($var)
    {
        GPBUtil::checkMessage($var, \Io\Intoto\Envelope::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->whichOneof("content");
    }

}

