<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_bundle.proto

namespace Dev\Sigstore\Bundle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Various timestamped counter signatures over the artifacts signature.
 * Currently only RFC3161 signatures are provided. More formats may be added
 * in the future.
 *
 * Generated from protobuf message <code>dev.sigstore.bundle.v1.TimestampVerificationData</code>
 */
class TimestampVerificationData extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of RFC3161 signed timestamps provided by the user.
     * This can be used when the entry has not been stored on a
     * transparency log, or in conjunction for a stronger trust model.
     * Clients MUST verify the hashed message in the message imprint
     * against the signature in the bundle.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.RFC3161SignedTimestamp rfc3161_timestamps = 1;</code>
     */
    private $rfc3161_timestamps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Dev\Sigstore\Common\V1\RFC3161SignedTimestamp>|\Google\Protobuf\Internal\RepeatedField $rfc3161_timestamps
     *           A list of RFC3161 signed timestamps provided by the user.
     *           This can be used when the entry has not been stored on a
     *           transparency log, or in conjunction for a stronger trust model.
     *           Clients MUST verify the hashed message in the message imprint
     *           against the signature in the bundle.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreBundle::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of RFC3161 signed timestamps provided by the user.
     * This can be used when the entry has not been stored on a
     * transparency log, or in conjunction for a stronger trust model.
     * Clients MUST verify the hashed message in the message imprint
     * against the signature in the bundle.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.RFC3161SignedTimestamp rfc3161_timestamps = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRfc3161Timestamps()
    {
        return $this->rfc3161_timestamps;
    }

    /**
     * A list of RFC3161 signed timestamps provided by the user.
     * This can be used when the entry has not been stored on a
     * transparency log, or in conjunction for a stronger trust model.
     * Clients MUST verify the hashed message in the message imprint
     * against the signature in the bundle.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.common.v1.RFC3161SignedTimestamp rfc3161_timestamps = 1;</code>
     * @param array<\Dev\Sigstore\Common\V1\RFC3161SignedTimestamp>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRfc3161Timestamps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Common\V1\RFC3161SignedTimestamp::class);
        $this->rfc3161_timestamps = $arr;

        return $this;
    }

}

