<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigstore_bundle.proto

namespace Dev\Sigstore\Bundle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * VerificationMaterial captures details on the materials used to verify
 * signatures. This message may be embedded in a DSSE envelope as a signature
 * extension. Specifically, the `ext` field of the extension will expect this
 * message when the signature extension is for Sigstore. This is identified by
 * the `kind` field in the extension, which must be set to
 * application/vnd.dev.sigstore.verificationmaterial;version=0.1 for Sigstore.
 * When used as a DSSE extension, if the `public_key` field is used to indicate
 * the key identifier, it MUST match the `keyid` field of the signature the
 * extension is attached to.
 *
 * Generated from protobuf message <code>dev.sigstore.bundle.v1.VerificationMaterial</code>
 */
class VerificationMaterial extends \Google\Protobuf\Internal\Message
{
    /**
     * An inclusion proof and an optional signed timestamp from the log.
     * Client verification libraries MAY provide an option to support v0.1
     * bundles for backwards compatibility, which may contain an inclusion
     * promise and not an inclusion proof. In this case, the client MUST
     * validate the promise.
     * Verifiers SHOULD NOT allow v0.1 bundles if they're used in an
     * ecosystem which never produced them.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.rekor.v1.TransparencyLogEntry tlog_entries = 3;</code>
     */
    private $tlog_entries;
    /**
     * Timestamp may also come from
     * tlog_entries.inclusion_promise.signed_entry_timestamp.
     *
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.TimestampVerificationData timestamp_verification_data = 4;</code>
     */
    protected $timestamp_verification_data = null;
    protected $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Dev\Sigstore\Common\V1\PublicKeyIdentifier $public_key
     *     @type \Dev\Sigstore\Common\V1\X509CertificateChain $x509_certificate_chain
     *     @type \Dev\Sigstore\Common\V1\X509Certificate $certificate
     *     @type array<\Dev\Sigstore\Rekor\V1\TransparencyLogEntry>|\Google\Protobuf\Internal\RepeatedField $tlog_entries
     *           An inclusion proof and an optional signed timestamp from the log.
     *           Client verification libraries MAY provide an option to support v0.1
     *           bundles for backwards compatibility, which may contain an inclusion
     *           promise and not an inclusion proof. In this case, the client MUST
     *           validate the promise.
     *           Verifiers SHOULD NOT allow v0.1 bundles if they're used in an
     *           ecosystem which never produced them.
     *     @type \Dev\Sigstore\Bundle\V1\TimestampVerificationData $timestamp_verification_data
     *           Timestamp may also come from
     *           tlog_entries.inclusion_promise.signed_entry_timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SigstoreBundle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKeyIdentifier public_key = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Common\V1\PublicKeyIdentifier|null
     */
    public function getPublicKey()
    {
        return $this->readOneof(1);
    }

    public function hasPublicKey()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.PublicKeyIdentifier public_key = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Common\V1\PublicKeyIdentifier $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\PublicKeyIdentifier::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.X509CertificateChain x509_certificate_chain = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Common\V1\X509CertificateChain|null
     */
    public function getX509CertificateChain()
    {
        return $this->readOneof(2);
    }

    public function hasX509CertificateChain()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.X509CertificateChain x509_certificate_chain = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Common\V1\X509CertificateChain $var
     * @return $this
     */
    public function setX509CertificateChain($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\X509CertificateChain::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.X509Certificate certificate = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Dev\Sigstore\Common\V1\X509Certificate|null
     */
    public function getCertificate()
    {
        return $this->readOneof(5);
    }

    public function hasCertificate()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.dev.sigstore.common.v1.X509Certificate certificate = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Dev\Sigstore\Common\V1\X509Certificate $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Common\V1\X509Certificate::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * An inclusion proof and an optional signed timestamp from the log.
     * Client verification libraries MAY provide an option to support v0.1
     * bundles for backwards compatibility, which may contain an inclusion
     * promise and not an inclusion proof. In this case, the client MUST
     * validate the promise.
     * Verifiers SHOULD NOT allow v0.1 bundles if they're used in an
     * ecosystem which never produced them.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.rekor.v1.TransparencyLogEntry tlog_entries = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTlogEntries()
    {
        return $this->tlog_entries;
    }

    /**
     * An inclusion proof and an optional signed timestamp from the log.
     * Client verification libraries MAY provide an option to support v0.1
     * bundles for backwards compatibility, which may contain an inclusion
     * promise and not an inclusion proof. In this case, the client MUST
     * validate the promise.
     * Verifiers SHOULD NOT allow v0.1 bundles if they're used in an
     * ecosystem which never produced them.
     *
     * Generated from protobuf field <code>repeated .dev.sigstore.rekor.v1.TransparencyLogEntry tlog_entries = 3;</code>
     * @param array<\Dev\Sigstore\Rekor\V1\TransparencyLogEntry>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTlogEntries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dev\Sigstore\Rekor\V1\TransparencyLogEntry::class);
        $this->tlog_entries = $arr;

        return $this;
    }

    /**
     * Timestamp may also come from
     * tlog_entries.inclusion_promise.signed_entry_timestamp.
     *
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.TimestampVerificationData timestamp_verification_data = 4;</code>
     * @return \Dev\Sigstore\Bundle\V1\TimestampVerificationData|null
     */
    public function getTimestampVerificationData()
    {
        return $this->timestamp_verification_data;
    }

    public function hasTimestampVerificationData()
    {
        return isset($this->timestamp_verification_data);
    }

    public function clearTimestampVerificationData()
    {
        unset($this->timestamp_verification_data);
    }

    /**
     * Timestamp may also come from
     * tlog_entries.inclusion_promise.signed_entry_timestamp.
     *
     * Generated from protobuf field <code>.dev.sigstore.bundle.v1.TimestampVerificationData timestamp_verification_data = 4;</code>
     * @param \Dev\Sigstore\Bundle\V1\TimestampVerificationData $var
     * @return $this
     */
    public function setTimestampVerificationData($var)
    {
        GPBUtil::checkMessage($var, \Dev\Sigstore\Bundle\V1\TimestampVerificationData::class);
        $this->timestamp_verification_data = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->whichOneof("content");
    }

}

